import type { DetailedFormulaProof } from './detailed-formula-proofs';
const p = (start: string, limits: string, ...steps: string[]): DetailedFormulaProof => ({ start, limits, steps });

export const starterProofs: Record<string, DetailedFormulaProof> = {
  'classical-mechanics-frames-and-motion': p('Choose two inertial frames with aligned axes, a shared origin at t=0, and relative velocity u along x.', 'Galilean transformations assume speeds much smaller than c. Relativistic frames do not share a universal time coordinate.',
    String.raw`At time t the moving frame’s origin has position ut in the original frame. An object’s distance from that origin is \(x'=x-ut\).`,
    String.raw`Subtract this relation at two times: \(\Delta x'=\Delta x-u\Delta t\). Galilean time gives \(\Delta t'=\Delta t\).`,
    String.raw`Divide by the common interval and take a derivative if needed: \(v'=v-u\). Since u is constant, differentiating again gives \(a'=a\).`),
  'classical-mechanics-force-diagrams': p('Newton’s empirical law relates net force to momentum change in an inertial frame. Isolate the body before summing forces.', 'The fixed-mass form does not automatically describe rockets or other variable-mass systems. Directions and reference frame must be consistent.',
    String.raw`Represent each force along a chosen axis by its signed component \(F_i\). Opposite directions have opposite signs.`,
    String.raw`Add them to get \(F_{\rm net}=\sum_iF_i=dp/dt\). For fixed m, \(dp/dt=d(mv)/dt=ma\).`,
    String.raw`Divide \(F_{\rm net}=ma\) by m>0: \(a=F_{\rm net}/m\). Balanced forces give zero acceleration, not necessarily zero velocity.`),
  'classical-mechanics-rotation': p('Torque is the rotational effect r×F about a specified pivot. Derive its lever-arm magnitude geometrically.', 'This magnitude is zero for a radial force. The sign or vector direction still needs the right-hand rule and chosen axis.',
    String.raw`The perpendicular distance from the pivot to the line of force is \(r_\perp=r\sin\phi\), where φ is the angle between r and F.`,
    String.raw`An infinitesimal rotation dθ moves the point tangentially by r dθ. Its work is \(dW=F\sin\phi\,r\,d\theta\).`,
    String.raw`Defining torque by \(dW=\tau\,d\theta\) gives \(\tau=rF\sin\phi=rF_\perp\). This agrees with the cross-product magnitude.`),
  'classical-mechanics-fluids-and-pressure': p('Pressure is normal force per area. A stationary thin fluid slab must have zero total vertical force.', 'Constant-density hydrostatics assumes a resting fluid and nearly uniform g. For changing density use an integral.',
    String.raw`Take a slab of area A and downward thickness dh. Its mass is \(dm=\rho A\,dh\), so weight is \(\rho gA\,dh\).`,
    String.raw`The lower pressure exceeds upper pressure by dP. Force balance is \(dP\,A=\rho gA\,dh\), hence \(dP=\rho g\,dh\).`,
    String.raw`Integrate from surface to depth h with constant ρ and g: \(P(h)-P(0)=\rho gh\). Thus the pressure increase is \(\Delta P=\rho gh\).`),
  'classical-mechanics-chaos-and-limits': p('Assume the toy recurrence dₙ₊₁=2dₙ with a specified initial separation d₀. This is a defined model, not a general law of chaos.', 'The recurrence eventually leaves any finite local range. Real Lyapunov growth rates need not be ln 2 per step.',
    String.raw`Apply the recurrence once: \(d_1=2d_0\). Apply it again: \(d_2=2d_1=2(2d_0)=2^2d_0\).`,
    String.raw`Assume \(d_n=2^nd_0\). The next step gives \(d_{n+1}=2d_n=2^{n+1}d_0\), establishing the induction step.`,
    String.raw`The base case n=0 and induction prove \(d_n=2^nd_0\) for all nonnegative integers n. Equivalently growth is \(d_0e^{n\ln2}\).`),
  'waves-sound-oscillation': p('Define period T as the duration of one complete repeating cycle and frequency f as the number of cycles per second.', 'A unique period requires a repeating signal. Both T and f are positive in this definition.',
    String.raw`After N complete identical cycles, elapsed time is \(t=NT\), by addition of N equal durations.`,
    String.raw`The cycle rate is \(f=N/t=N/(NT)=1/T\). The cycle count cancels.`,
    String.raw`Multiply by T to obtain \(fT=1\). Therefore \(T=1/f\); seconds per cycle and cycles per second are reciprocal units.`),
  'waves-sound-traveling-waves': p('A traveling periodic pattern advances one wavelength λ during one period T in a uniform medium.', 'For dispersive media this is phase speed and can differ from group speed. The frequency is positive and wavelength nonzero.',
    String.raw`Track one crest. In time T it reaches the former position of the next crest, a distance λ away, so \(v=\lambda/T\).`,
    String.raw`The cycle count definition gives \(f=1/T\). Substitute it to obtain \(v=f\lambda\).`,
    String.raw`Equivalently constant phase in \(kx-\omega t\) requires \(dx/dt=\omega/k\). With \(k=2\pi/\lambda\), \(\omega=2\pi f\), this again gives fλ.`),
  'waves-sound-superposition': p('Assume the governing wave equation is linear and both disturbances satisfy the same medium and boundary conditions.', 'Large-amplitude or nonlinear media may not obey superposition. Add displacements or amplitudes before calculating intensity.',
    String.raw`Write the linear wave operator as \(L[y]=\partial_t^2y-v^2\partial_x^2y\). Each independent wave satisfies \(L[y_i]=0\).`,
    String.raw`Derivatives distribute over sums, so \(L[y_1+y_2]=L[y_1]+L[y_2]=0\). Their sum is also a permitted wave.`,
    String.raw`At a shared position and time, displacement is \(y=y_1+y_2\). Equal amplitudes with opposite signs give zero displacement, while equal signs reinforce.`),
  'waves-sound-resonance': p('A string fixed at both ends has zero displacement at x=0 and x=L. Apply these boundary conditions to a standing sinusoid.', 'The formula describes the ideal fundamental string mode, not every resonator or every boundary condition.',
    String.raw`A standing mode can be written \(y=A\sin(kx)\cos(\omega t)\). The x=0 endpoint is automatically a node.`,
    String.raw`The x=L node requires \(\sin(kL)=0\), hence \(kL=n\pi\). The lowest nontrivial mode has n=1, so \(\lambda_1=2\pi/k=2L\).`,
    String.raw`Use \(v=f\lambda\): \(f_1=v/(2L)\). Higher ideal modes have \(f_n=nv/(2L)\).`),
  'waves-sound-sound-and-spectra': p('The bel is defined as the base-ten logarithm of a power or intensity ratio; a decibel is one tenth of a bel.', 'The intensity ratio must be positive and dimensionless. This is a scale definition, not a proof of subjective loudness.',
    String.raw`Form the ratio \(r=I/I_0\) using the same intensity units. A logarithm returns the exponent x in \(10^x=r\).`,
    String.raw`The level in bels is \(\log_{10}r\). Multiply by ten for decibels: \(\beta=10\log_{10}(I/I_0)\).`,
    String.raw`For I=I₀, r=1 and β=0. Increasing intensity tenfold adds \(10\log_{10}10=10\) dB; doubling adds about 3.01 dB.`),
  'thermodynamics-microscopic-temperature': p('In classical thermal equilibrium a quadratic kinetic term has a Boltzmann distribution. Derive its mean using a Gaussian integral.', 'This classical calculation can fail when quantum energy-level spacings matter. It assumes independent translational degrees of freedom.',
    String.raw`For one velocity component v, probability weight is \(e^{-\alpha v^2}\) with \(\alpha=m/(2k_BT)\). The mean square is the ratio \(\int v^2e^{-\alpha v^2}dv/\int e^{-\alpha v^2}dv\), over the real line.`,
    String.raw`Integrate the derivative of \(ve^{-\alpha v^2}\). Its boundary values vanish, giving \(\int e^{-\alpha v^2}dv=2\alpha\int v^2e^{-\alpha v^2}dv\). Thus \(\langle v^2\rangle=1/(2\alpha)=k_BT/m\).`,
    String.raw`Each direction therefore contributes \(m\langle v^2\rangle/2=k_BT/2\). Add x, y and z to obtain \(\langle K\rangle=3k_BT/2\).`),
  'thermodynamics-ideal-gas': p('Model N noninteracting classical point particles in a cube of side L, with elastic wall collisions and equilibrium velocity statistics.', 'The derivation neglects intermolecular forces and particle volume. Dense gases and quantum gases need other models.',
    String.raw`A particle reverses its normal velocity on a wall, transferring momentum \(2m|v_x|\). It returns to that wall after \(2L/|v_x|\), giving average force \(mv_x^2/L\).`,
    String.raw`Sum N particles and divide by area L²: \(P=Nm\langle v_x^2\rangle/L^3\). Since V=L³ and classical equilibrium gives \(m\langle v_x^2\rangle=k_BT\), \(PV=Nk_BT\).`,
    String.raw`Use N=nNₐ and R=NₐkB to get \(PV=nRT\). Divide by V>0 to obtain the displayed \(P=nRT/V\).`),
  'thermodynamics-first-law': p('Apply energy conservation to a closed system, with heat positive into it and work positive when done by it.', 'This sign convention must stay fixed. Changes of macroscopic kinetic and potential energy need inclusion when relevant.',
    String.raw`A small heat transfer δQ increases the system’s energy; work δW delivered outside decreases it. Conservation says \(dU=\delta Q-\delta W\).`,
    String.raw`Integrate between initial and final states: \(U_f-U_i=\int\delta Q-\int\delta W=Q-W\).`,
    String.raw`Define \(\Delta U=U_f-U_i\) to obtain \(\Delta U=Q-W\). Heat and work depend on the path; their difference equals a state-function change.`),
  'thermodynamics-entropy': p('Thermodynamics defines entropy through reversible heat: dS=δQrev/T, using absolute temperature.', 'Only reversible heat appears in this state-function construction. Actual irreversible transfers require a reversible comparison path.',
    String.raw`Along a reversible path, sum incremental changes: \(\Delta S=\int_i^f\delta Q_{\rm rev}/T\).`,
    String.raw`If temperature is constant and positive, take 1/T outside the integral: \(\Delta S=(1/T)\int_i^f\delta Q_{\rm rev}\).`,
    String.raw`The remaining integral is total reversible heat Qrev, giving \(\Delta S=Q_{\rm rev}/T\). For a changing temperature this constant-temperature simplification is unavailable.`),
  'thermodynamics-engines-and-limits': p('A reversible engine repeats its working-fluid state while moving heat between reservoirs at absolute temperatures Th>Tc>0.', 'The Carnot result is an upper bound. Irreversible engines generate entropy and have lower efficiency.',
    String.raw`Conservation over one cycle gives \(W=Q_h-Q_c\), where Qh is absorbed heat and Qc is rejected heat magnitude. Define \(\eta=W/Q_h\).`,
    String.raw`Reservoir entropy changes are \(-Q_h/T_h\) and \(+Q_c/T_c\). Reversibility requires their sum to vanish, so \(Q_c/Q_h=T_c/T_h\).`,
    String.raw`Substitute in \(\eta=1-Q_c/Q_h\) to get \(\eta_{\rm rev}=1-T_c/T_h\). For positive entropy production \(Q_c/Q_h\geq T_c/T_h\), so real η cannot exceed this value.`),
  'electromagnetism-charge-and-field': p('Take Coulomb’s electrostatic force law for a point source as empirical input and define electric field as force per test charge.', 'Point-charge electrostatics excludes radiation and magnetic forces. An ideal test charge does not alter the source distribution.',
    String.raw`For source charge q and test charge qt at separation r, \(\mathbf F=kqq_t\hat{\mathbf r}/r^2\). Signs determine attraction or repulsion.`,
    String.raw`Define \(\mathbf E=\mathbf F/q_t\) for nonzero qt, in the test-charge limit. Cancelling qt gives \(\mathbf E=kq\hat{\mathbf r}/r^2\).`,
    String.raw`The radial component is \(E_r=kq/r^2\). A different test charge then feels \(\mathbf F=q_t\mathbf E\), verifying that the field describes the source independently.`),
  'electromagnetism-potential': p('Define electrostatic potential difference as minus the electric-field line integral, with zero at infinity for a single isolated charge.', 'This reference is appropriate for an isolated point charge. Changing source configurations or time-dependent fields requires more care.',
    String.raw`Along a radial path, \(V(r)-V(\infty)=-\int_{\infty}^{r}E_r(s)\,ds=-kq\int_{\infty}^{r}s^{-2}\,ds\).`,
    String.raw`The antiderivative of s⁻² is −1/s, verified by differentiation. Thus \(V(r)= -kq[-1/s]_{\infty}^{r}=kq/r\).`,
    String.raw`Differentiate to check: \(-dV/dr=kq/r^2=E_r\). Potential keeps the sign of q, while potential differences set work per unit charge.`),
  'electromagnetism-current': p('Electric current counts signed charge crossing a chosen surface per time, with a specified positive normal direction.', 'The finite-interval expression is average current. Electron flow direction is opposite conventional current for negative carriers.',
    String.raw`Count net crossing charge: charge moving with the positive normal adds and charge moving against it subtracts, giving ΔQ.`,
    String.raw`Average rate over Δt>0 is \(I_{\rm avg}=\Delta Q/\Delta t\). Coulombs divided by seconds define amperes.`,
    String.raw`As the interval shrinks, instantaneous current is \(I=dQ/dt\). Conversely \(\Delta Q=\int I(t)\,dt\), reducing to IΔt for constant current.`),
  'electromagnetism-magnetic-force': p('Use the Lorentz force law as empirical input: magnetic force on a moving point charge is qv×B.', 'Magnetic force does no work on an isolated point charge because it is perpendicular to velocity. The displayed qvB magnitude assumes perpendicular motion.',
    String.raw`The cross product has magnitude \(F=|q|vB|\sin\phi|\), where φ is the angle between velocity and magnetic field.`,
    String.raw`For \(\phi=90^\circ\), \(\sin\phi=1\), so \(F=|q|vB\). For parallel motion the sine vanishes and so does the magnetic force.`,
    String.raw`Power is \(\mathbf F\cdot\mathbf v=q(\mathbf v\times\mathbf B)\cdot\mathbf v=0\). The field bends motion rather than changing the speed in this ideal case.`),
  'electromagnetism-maxwells-synthesis': p('Begin with Maxwell’s empirical vacuum equations, with no charges or currents, and consider a transverse plane wave.', 'E=cB is an amplitude relation for a propagating plane wave in vacuum. It does not hold for all static or near-source fields.',
    String.raw`Faraday’s law is \(\nabla\times\mathbf E=-\partial_t\mathbf B\); Ampère–Maxwell gives \(\nabla\times\mathbf B=\mu_0\epsilon_0\partial_t\mathbf E\). Vacuum divergence of E is zero.`,
    String.raw`Take the curl of Faraday and use \(\nabla\times(\nabla\times\mathbf E)=-\nabla^2\mathbf E\): \(\nabla^2\mathbf E=\mu_0\epsilon_0\partial_t^2\mathbf E\). Thus propagation speed is \(c=1/\sqrt{\mu_0\epsilon_0}\).`,
    String.raw`For \(E_y=E_0\cos(kx-\omega t)\), \(B_z=B_0\cos(kx-\omega t)\), Faraday’s law gives \(kE_0=\omega B_0\). With ω/k=c, \(E_0=cB_0\).`),
  'electronics-voltage-current-resistance': p('For an ohmic element, experiments establish a linear voltage-current relation. Resistance is its proportionality coefficient.', 'Ohm’s law is material dependent and can fail for diodes, heating resistors, and active components. R must be nonzero.',
    String.raw`For the chosen ohmic model define \(R=V/I\) at fixed conditions; its constancy makes \(V=IR\) hold over the modeled range.`,
    String.raw`Divide both sides by R: \(V/R=IR/R=I\), giving \(I=V/R\).`,
    String.raw`Since \(1\,\Omega=1\,\mathrm V/\mathrm A\), volts divided by ohms have ampere units. Doubling V at fixed R doubles I.`),
  'electronics-schematics-and-breadboards': p('For a static lumped circuit without significant induced magnetic voltage, potential returns to its original value around a closed loop.', 'The ideal loop rule neglects time-varying magnetic flux. Wires join common nodes only when their connections are actually continuous.',
    String.raw`Start at a node of potential V₀. The source raises potential by Vs, then the first and second resistors lower it by VR₁ and VR₂.`,
    String.raw`Returning to the same node gives \(V_0+V_s-V_{R_1}-V_{R_2}=V_0\). Subtract V₀ from both sides.`,
    String.raw`Rearrange \(V_s-V_{R_1}-V_{R_2}=0\) to \(V_s=V_{R_1}+V_{R_2}\). A schematic redraw preserves this equation if node connections are unchanged.`),
  'electronics-series-and-parallel': p('Use charge conservation at nodes, a common voltage across parallel branches, and Ohm’s law for each positive resistance.', 'Ideal series/parallel rules neglect wire resistance and parasitic components. Resistance zero needs treatment as a short, not reciprocal division.',
    String.raw`In series, both resistors carry current I and drops add: \(V=IR_1+IR_2=I(R_1+R_2)\). Thus \(R_{\rm eq}=R_1+R_2\).`,
    String.raw`In parallel, the shared voltage V drives \(I_1=V/R_1\), \(I_2=V/R_2\). Charge conservation gives \(I=I_1+I_2=V(1/R_1+1/R_2)\).`,
    String.raw`Define \(I=V/R_{\rm eq}\) and compare coefficients: \(1/R_{\rm eq}=1/R_1+1/R_2\), so \(R_{\rm eq}=R_1R_2/(R_1+R_2)\).`),
  'electronics-led-and-polarity': p('Approximate a forward-biased LED by a fixed positive voltage drop, with a series resistor limiting current.', 'A real LED has a nonlinear current-voltage curve. The fixed-drop approximation is not a component safety calculation or reverse-breakdown model.',
    String.raw`Follow the loop: supply rise Vs equals LED drop VLED plus resistor drop VR. Thus \(V_R=V_s-V_{\rm LED}\).`,
    String.raw`The resistor follows \(V_R=IR\). Substitute the loop expression and divide by R>0: \(I=(V_s-V_{\rm LED})/R\).`,
    String.raw`If Vs≤VLED or the LED is reverse oriented, this simple forward-only model uses zero current. Otherwise its positive current is set by the remaining voltage.`),
  'electronics-power-and-measurement': p('Voltage is energy transferred per unit charge; current is transferred charge per unit time.', 'Voltage and current must belong to the same element with a consistent passive sign convention. Pulsed power may need time averaging.',
    String.raw`A small charge dq crossing a voltage V transfers energy \(dE=V\,dq\).`,
    String.raw`Divide by dt: \(P=dE/dt=V(dq/dt)=VI\), which has units J/s or watts.`,
    String.raw`For an ohmic resistor insert V=IR to get \(P=I^2R\), or I=V/R to get \(P=V^2/R\). For R>0 dissipated power is nonnegative.`),
  'arduino-esp32-board-and-safe-wiring': p('Treat a HIGH output as an approximate pin voltage feeding a forward LED and a series resistor.', 'Real pin voltage falls under load and board current limits matter. The virtual ideal-pin estimate is not permission to connect an arbitrary load.',
    String.raw`Loop balance gives \(V_{\rm pin}=V_{\rm LED}+V_R\). Therefore the resistor sees \(V_R=V_{\rm pin}-V_{\rm LED}\).`,
    String.raw`Ohm’s law gives \(I_{\rm LED}\approx(V_{\rm pin}-V_{\rm LED})/R\) for forward conduction and R>0.`,
    String.raw`A LOW pin or an insufficient HIGH voltage gives no forward current in the approximation. Raising R reduces the current estimate in inverse proportion.`),
  'arduino-esp32-blink-sketch': p('A blink cycle includes one HIGH duration and one LOW duration. Period counts the time for both, not only the lit interval.', 'Software delays, execution time, and board scheduling can perturb real timing. Frequency refers to complete repeating cycles.',
    String.raw`If HIGH lasts ton and LOW lasts toff, a complete cycle lasts \(T=t_{\rm on}+t_{\rm off}\).`,
    String.raw`N cycles take NT seconds, so \(f=N/(NT)=1/T\).`,
    String.raw`For equal delays d, \(T=2d\) and \(f=1/(2d)\). A 0.5-second delay in each state therefore produces one full cycle per second.`),
  'arduino-esp32-button-input': p('Define an active-high digital encoding with a pull-down: released means LOW, and pressing connects the input to HIGH.', 'The piecewise rule is a wiring and coding definition. Pull-up inputs invert the meaning; real switches also need debouncing.',
    String.raw`The pull-down gives a known low reference when the button is open. Assign numeric code 0 to that released state.`,
    String.raw`Pressing closes a connection to the logic-high supply. Assign code 1 to the pressed state.`,
    String.raw`These exhaustive cases define \(x=1\) if pressed and \(x=0\) if released. There is no interpolation between ideal digital codes, although the electrical voltage is continuous.`),
  'arduino-esp32-pwm-output': p('A PWM waveform spends part of each fixed period HIGH and the rest LOW. Duty fraction measures the HIGH share.', 'Average output is not necessarily a true analog voltage. Load dynamics and switching speed determine whether an averaged model is useful.',
    String.raw`Split the period: \(T=t_{\rm HIGH}+t_{\rm LOW}\), with both durations nonnegative and T>0.`,
    String.raw`The fraction of time HIGH is \(D=t_{\rm HIGH}/T\), so \(0\leq D\leq1\). A percentage is 100D.`,
    String.raw`For levels VH and VL, integrate over a cycle: \(\bar V=(V_Ht_{\rm HIGH}+V_Lt_{\rm LOW})/T=DV_H+(1-D)V_L\). For VL=0 this is DVH.`),
  'arduino-esp32-analog-sensor': p('Use the stated ideal endpoint-mapped ADC model: b binary bits span 2ᵇ codes from 0 to 2ᵇ−1.', 'This rounded endpoint mapping is an educational approximation. Real ADC transition thresholds, references, noise, and board calibration can differ.',
    String.raw`Each of b bits has two choices. Their independent combinations total \(2^b\); indexing from zero makes the largest code \(n_{\max}=2^b-1\).`,
    String.raw`Normalize voltage to a dimensionless fraction \(r=V_{\rm in}/V_{\rm ref}\) for Vref>0, and clamp r into [0,1].`,
    String.raw`Linear endpoint scaling gives real-valued code \(rn_{\max}\). The nearest integer is \(n\approx\mathrm{round}[(V_{\rm in}/V_{\rm ref})(2^b-1)]\).`),
  'optics-reflection': p('In a uniform medium, Fermat’s principle selects a stationary travel-time path. Reflect the destination across a flat mirror.', 'Geometric optics assumes a smooth mirror and wavelengths small compared with the geometry. Angles are measured from the normal.',
    String.raw`For any reflection point P on the mirror, distance to destination B equals distance to its mirror image B′. Thus \(|AP|+|PB|=|AP|+|PB'|\).`,
    String.raw`With a constant speed, the shortest time is the shortest length. A straight segment from A to B′ minimizes this sum and fixes P at its intersection with the mirror.`,
    String.raw`That straight line has equal angles with the mirror normal on either side after reflecting B′ back to B. Therefore \(\theta_r=\theta_i\).`),
  'optics-refraction': p('Use Fermat’s stationary travel-time principle for two homogeneous media with speeds c/n₁ and c/n₂.', 'Snell’s law here uses isotropic media and geometric optics. Total internal reflection occurs when no real transmitted angle satisfies it.',
    String.raw`Let endpoints have perpendicular distances a,b from a flat interface and along-interface separation d. A crossing at coordinate x has time \(t(x)=[n_1\sqrt{a^2+x^2}+n_2\sqrt{b^2+(d-x)^2}]/c\).`,
    String.raw`Differentiate and set dt/dx=0: \(n_1x/\sqrt{a^2+x^2}=n_2(d-x)/\sqrt{b^2+(d-x)^2}\).`,
    String.raw`The geometric ratios are sine of the angles to the normal. Thus \(n_1\sin\theta_1=n_2\sin\theta_2\), the displayed interface rule.`),
  'optics-lenses': p('For a converging thin lens, use paraxial rays: one through the optical center and one parallel to the axis refracted through the focal point.', 'The triangle argument assumes a thin lens and small ray angles. Signed distances extend it to virtual images; diffraction and aberrations are omitted.',
    String.raw`Let the object height be h and the inverted image height magnitude h′. The central ray’s similar triangles give \(h'/h=d_i/d_o\).`,
    String.raw`The parallel ray meets the lens at height h and crosses the axis at f. Its triangles give \(h'/h=(d_i-f)/f=d_i/f-1\).`,
    String.raw`Equate the ratios: \(d_i/d_o=d_i/f-1\). Divide by nonzero di and rearrange: \(1/d_o+1/d_i=1/f\), hence \(1/d_i=1/f-1/d_o\).`),
  'optics-interference': p('Two coherent waves of the same frequency acquire different phase when they travel different path lengths.', 'The integer-path rule is constructive interference for equal initial phase. Additional source or reflection phase shifts change the condition.',
    String.raw`A complete wavelength advances phase by 2π. A path difference ΔL therefore gives \(\Delta\phi=2\pi\Delta L/\lambda\).`,
    String.raw`Equal waves add as \(A\cos\phi+A\cos(\phi+\Delta\phi)=2A\cos(\Delta\phi/2)\cos(\phi+\Delta\phi/2)\).`,
    String.raw`The largest combined amplitude magnitude occurs for \(\Delta\phi=2\pi m\), with integer m. Substitute the path-phase relation to get \(\Delta L=m\lambda\).`),
  'optics-photons-and-imaging': p('Take the quantum energy-frequency relation as a physical postulate, and relate wave frequency to wavelength in vacuum.', 'The relation is experimentally supported quantum physics, not a theorem of classical wave optics. Frequency, not brightness, sets each photon’s energy.',
    String.raw`Quantizing one electromagnetic mode gives adjacent occupation energies separated by \(\hbar\omega\). One photon adds one such excitation.`,
    String.raw`Angular frequency advances phase in radians: \(\omega=2\pi f\). Planck’s constants satisfy \(h=2\pi\hbar\), so \(\hbar\omega=hf\).`,
    String.raw`In vacuum c=fλ, hence \(E=hf=hc/\lambda\). N photons at that frequency carry total energy Nhf, so brighter light need not have higher energy per photon.`),
  'relativity-events-and-frames': p('Choose the invariant vacuum light speed c as the reference speed and a signed velocity v along one axis.', 'β is a dimensionless definition, not a new force law. Massive inertial motion has |β|<1; the sign follows the chosen axis.',
    String.raw`Compare like quantities by forming \(\beta=v/c\). Both numerator and denominator have speed units, which cancel.`,
    String.raw`Multiplying by c reverses the definition: \(v=\beta c\). Thus β=0.5 means half the light speed along the positive axis.`,
    String.raw`Changing the direction replaces v by −v and β by −β. Expressions involving β², such as the Lorentz factor, remain unchanged.`),
  'relativity-light-clock-dilation': p('Assume light has speed c in every inertial frame. Use a clock made of a light pulse bouncing between mirrors separated perpendicular to motion.', 'The clock’s proper time is measured in its rest frame. The Lorentz factor requires |v|<c and does not describe an arbitrary coordinate time in curved spacetime.',
    String.raw`One half-tick in the clock frame covers mirror spacing L, giving \(\Delta\tau=L/c\). In a frame where the clock moves at v, the pulse follows a diagonal.`,
    String.raw`During half-tick Δt, horizontal travel is vΔt and diagonal light distance is cΔt. Pythagoras gives \((c\Delta t)^2=L^2+(v\Delta t)^2\).`,
    String.raw`Rearrange \((c^2-v^2)\Delta t^2=L^2=c^2\Delta\tau^2\). Divide by c² and take positive time intervals: \(\Delta t=\Delta\tau/\sqrt{1-v^2/c^2}\).`,
    String.raw`Define \(\beta=v/c\) and \(\gamma=\Delta t/\Delta\tau\). This yields \(\gamma=(1-\beta^2)^{-1/2}\).`),
  'relativity-length-and-simultaneity': p('Use Lorentz transformations fixed by invariant light speed, with a rod at rest in the primed frame and proper length L₀.', 'Endpoint positions must be measured simultaneously in the measuring frame. Only the component parallel to motion contracts.',
    String.raw`The spatial Lorentz transformation is \(x'=\gamma(x-vt)\), and the temporal one is \(t'=\gamma(t-vx/c^2)\).`,
    String.raw`Take two endpoint events at equal unprimed time, Δt=0. Subtraction gives \(\Delta x'=\gamma\Delta x\).`,
    String.raw`The rod’s fixed primed endpoint separation is L₀ and the unprimed measured length is L, so \(L_0=\gamma L\), or \(L=L_0/\gamma\). The events have \(\Delta t'=-\gamma vL/c^2\), showing why simultaneity matters.`),
  'relativity-energy-momentum': p('Special-relativistic momentum is p=γmv for a constant rest mass. Use work as the change in energy.', 'The relativistic momentum premise follows the Lorentz symmetry of the model. Rest energy is fixed by four-momentum normalization, not an arbitrary kinetic-energy offset.',
    String.raw`In one dimension \(dK=F\,dx=v\,dp\). Differentiating \(p=mv/\sqrt{1-v^2/c^2}\) gives \(dp/dv=m\gamma^3\).`,
    String.raw`Hence \(dK=m\gamma^3v\,dv\). Since \(d\gamma/dv=\gamma^3v/c^2\), integrate from rest to obtain \(K=mc^2(\gamma-1)\).`,
    String.raw`The invariant four-momentum assigns rest energy \(E_0=mc^2\). Adding it gives \(E=K+E_0=\gamma mc^2\), while p=γmv.`),
  'relativity-curved-spacetime': p('For a weak static gravitational field, proper clock rate follows the metric factor √(1+2Φ/c²), where Φ is gravitational potential.', 'This is a leading-order fractional clock-rate difference for small heights and |Φ|≪c². It is not an exact strong-field formula.',
    String.raw`A stationary clock has \(d\tau/dt\approx\sqrt{1+2\Phi/c^2}\). The expansion \(\sqrt{1+z}=1+z/2+O(z^2)\) gives \(d\tau/dt\approx1+\Phi/c^2\).`,
    String.raw`Compare upper and lower clock rates. To first order their fractional difference is \(\delta\approx(\Phi_{\rm upper}-\Phi_{\rm lower})/c^2\).`,
    String.raw`Near Earth over small height h, \(\Delta\Phi\approx gh\). Thus \(\delta\approx gh/c^2\): the upper clock runs faster relative to the lower one.`),
  'quantum-light-quanta': p('Use the quantized harmonic-oscillator description of one free electromagnetic mode. Quantization is a physical postulate.', 'A classical wave alone does not prove photon quantization. The zero-point baseline does not add to the energy of each absorbed photon.',
    String.raw`Mode energies are \(E_n=\hbar\omega(n+1/2)\). Adding one excitation changes n to n+1.`,
    String.raw`Subtract adjacent levels: \(E_{n+1}-E_n=\hbar\omega[(n+3/2)-(n+1/2)]=\hbar\omega\).`,
    String.raw`Since \(\omega=2\pi f\) and \(h=2\pi\hbar\), one excitation carries \(E=hf\). Frequency sets each photon’s energy; occupation number sets how many photons there are.`),
  'quantum-build-a-wavefunction': p('Use the Born rule as a quantum probability postulate and a normalizable complex position amplitude ψ(x).', 'The algebra explains the positive magnitude and normalization; it does not prove the Born postulate from classical mechanics.',
    String.raw`Write \(\psi=a+ib\), with real a,b. Complex conjugation gives \(\psi^*=a-ib\).`,
    String.raw`Multiply: \(\psi^*\psi=(a-ib)(a+ib)=a^2+b^2\geq0\), because i²=−1 and cross terms cancel.`,
    String.raw`For an unnormalized amplitude φ, let \(N=\int|\phi|^2dx>0\) and set \(\psi=\phi/\sqrt N\). Then \(\rho=|\psi|^2\) integrates to one and interval probability is its area.`),
  'quantum-measurement-probabilities': p('Measurement outcomes form a complete set of mutually exclusive events with probabilities pᵢ. Use finite probability additivity.', 'Only disjoint outcomes can be added directly. Coherent quantum amplitudes must first be combined before squaring when alternatives are not distinguished.',
    String.raw`Normalization is \(\sum_i p_i=1\), with \(p_i\geq0\). An event A is a subset of the listed outcomes.`,
    String.raw`Because distinct outcomes cannot occur together in one measurement, their intersections are empty. The probability union rule has no overlap term.`,
    String.raw`Repeatedly applying that rule gives \(P(A)=\sum_{i\in A}p_i\). The empty subset has probability zero, and the complete subset has probability one.`),
  'quantum-uncertainty': p('Use a normalized wavefunction, position operator x, momentum operator p=−iℏ∂x, and finite variances. The operators are Hermitian on the chosen domain.', 'Δx and Δp are standard deviations of one state, not instrument errors. Boundary conditions must make integrations by parts valid.',
    String.raw`Center the operators: \(A=x-\langle x\rangle\), \(B=p-\langle p\rangle\). Vectors a=Aψ and b=Bψ have squared norms \(\|a\|^2=(\Delta x)^2\), \(\|b\|^2=(\Delta p)^2\).`,
    String.raw`The nonnegative norm of \(a-\lambda b\), minimized at \(\lambda=\langle b,a\rangle/\|b\|^2\), yields \(\|a\|^2\|b\|^2\geq|\langle a,b\rangle|^2\). This is Cauchy–Schwarz.`,
    String.raw`For Hermitian A,B, \(\mathrm{Im}\langle a,b\rangle=\langle[A,B]\rangle/(2i)\). Directly acting on ψ gives \([x,-i\hbar\partial_x]\psi=i\hbar\psi\), so its magnitude is ℏ/2.`,
    String.raw`Since \(|z|^2\geq(\mathrm{Im}\,z)^2\), combine the bounds: \((\Delta x)^2(\Delta p)^2\geq\hbar^2/4\). Nonnegative square roots give \(\Delta x\Delta p\geq\hbar/2\).`),
  'quantum-tunneling': p('Use the stationary one-dimensional Schrödinger equation inside a constant barrier V₀ with particle energy E<V₀.', 'The displayed transmission is only the dominant thick-barrier exponential. Exact boundary matching supplies an energy-dependent prefactor.',
    String.raw`Inside the barrier, \(-\hbar^2\psi''/(2m)+V_0\psi=E\psi\), so \(\psi''=\kappa^2\psi\), with \(\kappa=\sqrt{2m(V_0-E)}/\hbar\).`,
    String.raw`Solutions are \(Ae^{\kappa x}+Be^{-\kappa x}\). The decreasing component crossing width a loses an amplitude factor \(e^{-\kappa a}\).`,
    String.raw`Probability flux transmission scales with squared amplitude, giving \(T\propto e^{-2\kappa a}\). In the equal-exterior-potential barrier, exact matching gives \(T=[1+V_0^2\sinh^2(\kappa a)/(4E(V_0-E))]^{-1}\).`,
    String.raw`For κa≫1, \(\sinh^2(\kappa a)\approx e^{2\kappa a}/4\). The exponential controls the suppression; the lesson keeps that scale and omits its prefactor.`),
  'atomic-molecular-spectra': p('Use energy conservation for an atom emitting one photon while changing between stationary energy levels.', 'Ignore recoil at introductory accuracy. Real spectral lines have widths, selection rules, and environmental shifts.',
    String.raw`Before emission total energy is Ei. Afterward it is atomic energy Ef plus photon energy Eγ, so \(E_i=E_f+E_\gamma\).`,
    String.raw`Subtract Ef to get \(E_\gamma=E_i-E_f\), positive for a downward transition.`,
    String.raw`Photon quantization gives \(hf=E_i-E_f\); in vacuum wavelength is \(\lambda=hc/(E_i-E_f)\). Different level gaps therefore produce different spectral lines.`),
  'atomic-molecular-bohr-scale': p('For the historical hydrogen Bohr model, assume a fixed proton, circular Coulomb motion, and quantized angular momentum mvr=nℏ.', 'This scale model is not a literal modern electron trajectory. It omits reduced mass, fine structure, and multi-electron interactions.',
    String.raw`Coulomb force balance gives \(mv^2/r=ke^2/r^2\). Quantization gives \(v=n\hbar/(mr)\).`,
    String.raw`Substitute velocity into force balance and solve: \(r_n=n^2\hbar^2/(mke^2)\). Thus allowed radius grows as n².`,
    String.raw`Kinetic energy is \(K=mv^2/2=ke^2/(2r_n)\); potential is \(U=-ke^2/r_n\). Their sum is \(E_n=-ke^2/(2r_n)=-mk^2e^4/(2\hbar^2n^2)\).`,
    String.raw`Hydrogen constants give the coefficient about 13.6 eV, so \(E_n\approx-13.6\,\mathrm{eV}/n^2\). The zero reference is separated proton and electron.`),
  'atomic-molecular-orbitals': p('Treat A and B as two disjoint outcomes that exhaust the possible results of the specified normalized measurement.', 'Real orbital distributions are not generally two-point distributions. This lesson’s two-outcome example is a probability illustration.',
    String.raw`Normalization requires total probability one, represented by \(\langle\psi|\psi\rangle=1\).`,
    String.raw`For complete orthogonal outcomes, projectors satisfy \(\Pi_A+\Pi_B=1\). Born probabilities are \(P(A)=\langle\psi|\Pi_A|\psi\rangle\), and similarly for B.`,
    String.raw`Add the two expressions: \(P(A)+P(B)=\langle\psi|(\Pi_A+\Pi_B)|\psi\rangle=1\). Hence either probability determines the other as its complement.`),
  'atomic-molecular-bonds': p('Define bond dissociation energy using a bound state and separated constituents with the same specified reference convention.', 'Electronic state, zero-point vibration, and thermodynamic reference conditions affect quoted bond energies.',
    String.raw`Take the separated state as energy Esep and the bound state as Ebound. Stable binding means Ebound<Esep.`,
    String.raw`Energy conservation for separating the constituents requires input \(D=E_{\rm sep}-E_{\rm bound}>0\).`,
    String.raw`If the reference is shifted by a constant C, \((E_{\rm sep}+C)-(E_{\rm bound}+C)=D\). The difference, not either absolute level, is physically relevant.`),
  'atomic-molecular-lasers': p('Use a simplified two-level model with equal degeneracies and equal stimulated-emission and absorption coefficients.', 'Unequal degeneracies require N₂/g₂>N₁/g₁, and actual laser gain also depends on cross sections, losses, and pumping.',
    String.raw`For radiation energy density u, stimulated emission rate is \(R_{\rm em}=BN_2u\); absorption rate is \(R_{\rm abs}=BN_1u\).`,
    String.raw`Their difference is \(R_{\rm net}=Bu(N_2-N_1)\), with B and u nonnegative.`,
    String.raw`Positive stimulated gain requires \(N_2-N_1>0\), or \(N_2>N_1\). Spontaneous emission can occur without inversion, but does not replace this gain condition.`),
  'nuclear-binding': p('Use mass-energy equivalence for a nucleus and its separated constituents, compared at rest under consistent particle conventions.', 'Use nuclear or atomic masses consistently; mixing conventions introduces electron-mass errors. The mass-energy law is a physical premise.',
    String.raw`Separated constituent rest energy is \(E_{\rm sep}=\sum_i m_ic^2\). Bound nucleus rest energy is \(E_{\rm nuc}=Mc^2\).`,
    String.raw`Binding releases their energy difference: \(B=E_{\rm sep}-E_{\rm nuc}=(\sum_i m_i-M)c^2\).`,
    String.raw`Define mass defect \(\Delta m=\sum_i m_i-M\) to obtain \(B=\Delta mc^2\). A positive B is the energy needed to undo the binding under that reference.`),
  'nuclear-decay': p('Each surviving nucleus has an independent constant probability λdt of decaying during a very short interval dt.', 'Activity is an expected rate; individual decays are random. Chains and time-varying decay conditions need coupled models.',
    String.raw`For N surviving nuclei, expected losses are \(-dN=\lambda N\,dt\), by adding their independent probabilities.`,
    String.raw`Divide by dt to get \(dN/dt=-\lambda N\). Activity is the positive expected loss rate \(A=-dN/dt=\lambda N\).`,
    String.raw`For constant λ, integration gives \(N=N_0e^{-\lambda t}\), hence \(A(t)=\lambda N_0e^{-\lambda t}\). Units of λ are inverse seconds and activity is decays per second.`),
  'nuclear-half-life': p('Independent constant-rate decay gives dN/dt=−λN. Half-life is the time that reduces the expected population by half.', 'The exponential describes the expected population, not an exact schedule of individual decay events. λ must be positive.',
    String.raw`Separate variables: \(dN/N=-\lambda\,dt\). Integrate from N₀ at zero to N at t: \(\ln(N/N_0)=-\lambda t\).`,
    String.raw`Exponentiate to get \(N=N_0e^{-\lambda t}\). At t=t½ set N/N₀=1/2, so \(-\lambda t_{1/2}=\ln(1/2)=-\ln2\).`,
    String.raw`Thus \(\lambda=\ln2/t_{1/2}\). Substitution gives \(N=N_0e^{-(\ln2)t/t_{1/2}}=N_0\,2^{-t/t_{1/2}}\).`),
  'nuclear-fission': p('Compare the rest masses of a complete initial and final reaction state, using conservation of total relativistic energy.', 'Q is available reaction energy, not necessarily all deposited heat. Recoil, escaping particles, and excited products must be accounted for.',
    String.raw`Total energy before and after obeys \(m_ic^2+K_i=m_fc^2+K_f\), with all masses and kinetic energies included.`,
    String.raw`Subtract initial kinetic energy and final rest energy: \(K_f-K_i=(m_i-m_f)c^2\).`,
    String.raw`Define \(Q=K_f-K_i\) for this complete bookkeeping. Then \(Q=(m_i-m_f)c^2\), positive for an exothermic reaction.`),
  'nuclear-fusion': p('Assume each of Nᵣ counted identical reactions releases energy Q. Total energy is additive over independent reaction events.', 'Different reaction channels may have different Q values. Energy carried away by neutrinos is not automatically useful deposited energy.',
    String.raw`One event adds Q. Two events add \(Q+Q=2Q\), with matching energy units.`,
    String.raw`Sum over Nᵣ events: \(E=\sum_{j=1}^{N_r}Q=N_rQ\). This is multiplication as repeated addition.`,
    String.raw`For mixed channels replace the common Q by each event’s \(Q_j\), giving \(E=\sum_jQ_j\). For efficiency ε, usable energy would instead be εE.`),
  'particle-relativistic-particles': p('Use the Lorentz-invariant four-momentum of a free particle, with E=γmc² and p=γmv for nonzero rest mass.', 'The positive-energy branch is used. The invariant relation extends to massless particles even though their rest frame and γ are undefined.',
    String.raw`Subtract squared quantities: \(E^2-p^2c^2=\gamma^2m^2c^4-\gamma^2m^2v^2c^2=\gamma^2m^2c^4(1-v^2/c^2)\).`,
    String.raw`Because \(\gamma^2=1/(1-v^2/c^2)\), the product reduces to \(m^2c^4\). Rearranging gives \(E^2=(pc)^2+(mc^2)^2\).`,
    String.raw`At p=0 take the positive root to get E=mc². For m=0, the same invariant gives E=|p|c, matching free photons.`),
  'particle-quantum-fields': p('One free bosonic field mode behaves as a quantized harmonic oscillator. Adopt canonical quantum commutation as the model premise.', 'This derivation describes free mode spacing, not the complete interacting field theory or particle creation probabilities.',
    String.raw`Define ladder operators with \([a,a^\dagger]=1\). The mode Hamiltonian is \(H=\hbar\omega(a^\dagger a+1/2)\).`,
    String.raw`Occupation states satisfy \(a^\dagger a|n\rangle=n|n\rangle\), so \(E_n=\hbar\omega(n+1/2)\).`,
    String.raw`Subtract adjacent energies: \(\Delta E=E_{n+1}-E_n=\hbar\omega=hf\), using \(\omega=2\pi f\) and \(h=2\pi\hbar\). The shared zero-point term cancels.`),
  'particle-symmetries': p('Electric charge conservation is an experimentally tested physical principle associated with gauge symmetry.', 'Charge conservation constrains reactions but does not by itself guarantee a reaction occurs; energy and other quantum numbers also matter.',
    String.raw`Local conservation is \(\partial_t\rho+\nabla\cdot\mathbf J=0\), with charge density ρ and charge-current density J.`,
    String.raw`Integrate over a volume: \(dQ/dt=-\oint\mathbf J\cdot d\mathbf A\). The divergence theorem converts the volume divergence to boundary flux.`,
    String.raw`For an isolated reaction with no uncounted boundary flux, dQ/dt=0. Summing particle charges before and after therefore gives \(Q_{\rm before}=Q_{\rm after}\).`),
  'particle-standard-model': p('Use the proton’s simplified uud valence-quark content and the Standard Model charge assignments for up and down quarks.', 'Valence content is not the complete proton wavefunction. Gluons and sea quarks contribute dynamics while preserving the total conserved charge.',
    String.raw`Electric charge adds over constituents. Two up quarks and one down quark give \(Q_p=Q_u+Q_u+Q_d=2Q_u+Q_d\).`,
    String.raw`Insert the assignments \(Q_u=2e/3\) and \(Q_d=-e/3\): \(Q_p=2(2e/3)-e/3\).`,
    String.raw`Combine thirds: \(Q_p=(4-1)e/3=e\). This verifies the proton charge within the stated composition and assignments rather than deriving quark charges from arithmetic.`),
  'particle-neutrinos-and-open-questions': p('Use a two-state mixing model with orthonormal propagation states |1⟩,|2⟩ and mixing angle θ.', 'Real neutrinos have three flavors and can undergo matter effects. Here φ is half the relative propagation phase.',
    String.raw`Define flavor states \(|\alpha\rangle=\cos\theta|1\rangle+\sin\theta|2\rangle\) and \(|\beta\rangle=-\sin\theta|1\rangle+\cos\theta|2\rangle\).`,
    String.raw`After propagation the first state is \(\cos\theta e^{-i\phi_1}|1\rangle+\sin\theta e^{-i\phi_2}|2\rangle\). Its overlap with β is \(\sin\theta\cos\theta(e^{-i\phi_2}-e^{-i\phi_1})\).`,
    String.raw`The phase difference has squared magnitude \(4\sin^2[(\phi_2-\phi_1)/2]\). With \(\phi=(\phi_2-\phi_1)/2\) and \(2\sin\theta\cos\theta=\sin2\theta\), the Born probability is \(P=\sin^2(2\theta)\sin^2\phi\).`),
  'condensed-matter-lattices': p('Define an ideal one-dimensional lattice as equally spaced sites, spacing a>0, with site zero at the coordinate origin.', 'Real crystals can have multiple sites per unit cell, defects, thermal motion, and more than one spatial dimension.',
    String.raw`The recurrence for successive coordinates is \(x_{n+1}=x_n+a\), starting from \(x_0=0\).`,
    String.raw`Iterating adds a exactly n times: \(x_n=\sum_{j=1}^n a=na\). Negative integer n labels sites on the other side of the origin.`,
    String.raw`A translated origin x₀ would give \(x_n=x_0+na\). Adjacent differences stay \(x_{n+1}-x_n=a\), which is the defining lattice spacing.`),
  'condensed-matter-bands': p('Define the valence-band edge Ev and conduction-band edge Ec as reference single-particle energy levels in the band model.', 'A band gap is not automatically the measured optical absorption threshold; excitons and indirect transitions can change the connection.',
    String.raw`Promoting a carrier from the valence edge to the conduction edge changes its energy from Ev to Ec.`,
    String.raw`Required energy gain is final minus initial: \(E_g=E_c-E_v\). It is positive for an ordinary separated gap.`,
    String.raw`Changing the energy zero by C leaves \((E_c+C)-(E_v+C)=E_g\). Thus the gap is a reference-independent energy difference.`),
  'condensed-matter-fermi-statistics': p('A single fermion state has occupancy n=0 or n=1. In grand-canonical equilibrium its weight is exp[−(E−μ)n/(kBT)].', 'This formula assumes independent effective states in thermal equilibrium. At T=0 use the limiting step distribution; interacting systems may need a different description.',
    String.raw`Let \(z=(E-\mu)/(k_BT)\) with T>0. Empty weight is 1, occupied weight is \(e^{-z}\), so the state partition sum is \(Z=1+e^{-z}\).`,
    String.raw`The mean occupancy is \(f=(0\times1+1\times e^{-z})/Z=e^{-z}/(1+e^{-z})\).`,
    String.raw`Multiply top and bottom by eᶻ: \(f=1/(e^z+1)\). At E=μ this gives 1/2; far below μ occupation tends to one, and far above it tends to zero.`),
  'condensed-matter-semiconductors': p('Use a one-carrier Drude model: particles of number density n drift through a material under an electric field, with mobility μe.', 'The displayed expression uses positive elementary-charge magnitude e and one carrier type. Real semiconductors also have holes, scattering, and temperature dependence.',
    String.raw`In time dt, carriers with drift-speed magnitude vd cross a slab of volume \(A v_d\,dt\). Its charge magnitude is \(dq=neA v_d\,dt\).`,
    String.raw`Current density magnitude is \(J=(dq/dt)/A=nev_d\). Mobility defines \(v_d=\mu_e E\) in the linear regime.`,
    String.raw`Substitute to get \(J=ne\mu_e E\). Comparing with the macroscopic definition \(J=\sigma E\) identifies \(\sigma=ne\mu_e\).`),
  'condensed-matter-superconductivity': p('Start from the weak-coupling, constant-density-of-states BCS gap equation with attractive coupling λ and cutoff energy Ω.', 'The gap equation is the mean-field model premise. The technical integral used here is stated explicitly; this is not a derivation of the full many-body BCS Hamiltonian.',
    String.raw`At zero temperature the gap equation is \(1/\lambda=\int_0^\Omega d\epsilon/\sqrt{\epsilon^2+\Delta_0^2}=\operatorname{asinh}(\Omega/\Delta_0)\approx\ln(2\Omega/\Delta_0)\) for Ω≫Δ₀.`,
    String.raw`At Tc the gap vanishes: \(1/\lambda=\int_0^\Omega\tanh[\epsilon/(2k_BT_c)]\,d\epsilon/\epsilon\). For Ω≫kBTc the integral evaluates to \(\ln[2e^{\gamma_E}\Omega/(\pi k_BT_c)]\), where γE≈0.577 is Euler’s constant.`,
    String.raw`Equate the logarithms and cancel 2Ω: \(\Delta_0=\pi e^{-\gamma_E}k_BT_c\approx1.764k_BT_c\). The numerical factor belongs to this weak-coupling model, not all superconductors.`),
  'astrophysics-stellar-light': p('Assume a spherical star with effective temperature T emitting approximately as a blackbody. Start with Planck’s equilibrium spectrum.', 'Real spectra have lines and atmospheres. Effective temperature describes the integrated radiative flux, not every layer’s actual temperature.',
    String.raw`Blackbody energy density per frequency is \(u_\nu=8\pi h\nu^3/[c^3(e^{h\nu/(k_BT)}-1)]\). Isotropic outgoing flux is c/4 times its frequency integral.`,
    String.raw`Set x=hν/(kBT). Then \(F=2\pi k_B^4T^4/(h^3c^2)\int_0^\infty x^3/(e^x-1)\,dx\). The integral is π⁴/15, so \(F=\sigma T^4\), with \(\sigma=2\pi^5k_B^4/(15h^3c^2)\).`,
    String.raw`Multiply flux by the spherical area \(4\pi R^2\): \(L=4\pi R^2\sigma T^4\). This converts power per area to total power.`),
  'astrophysics-hydrostatic-balance': p('A thin stellar layer in static equilibrium has no net radial force. Choose radius increasing outward.', 'The finite-difference expression assumes nearly constant density and gravity across the layer. A whole star requires coupled structural equations.',
    String.raw`A layer of area A and thickness dr has mass \(dm=\rho A\,dr\) and inward weight \(\rho gA\,dr\).`,
    String.raw`Pressure at the inner face pushes outward with PA; the outer face pushes inward with (P+dP)A. Net outward pressure force is −dP·A.`,
    String.raw`Balance forces: \(-dP\,A=\rho gA\,dr\). Cancel A to get \(dP/dr=-\rho g\), or \(\Delta P\approx-\rho g\Delta r\) over a thin layer.`),
  'astrophysics-fusion': p('Define ε as the fraction of the initial fuel rest mass converted into released reaction energy, and use mass-energy conservation.', 'This is energy accounting given ε, not a derivation of nuclear reaction rates. Usable stellar energy depends on reaction channels and losses.',
    String.raw`Initial fuel mass is m. If converted fraction is ε, the mass decrease is \(\Delta m=\epsilon m\).`,
    String.raw`Mass-energy conservation assigns released energy \(E=\Delta mc^2\). Substitution gives \(E=\epsilon mc^2\).`,
    String.raw`For a mixture of reaction channels ε is an appropriate averaged fraction. Escaping neutrino energy or inaccessible fuel reduces energy available for sustained light.`),
  'astrophysics-stellar-evolution': p('Luminosity is radiated energy per time. Estimate a fuel-limited lifetime from an available energy budget.', 'This is an order-of-magnitude estimate. Luminosity evolves and only part of a star’s mass is usable fuel in a given burning stage.',
    String.raw`For constant luminosity L, energy emitted over t is \(E_{\rm emitted}=\int_0^tL\,dt'=Lt\).`,
    String.raw`If the stage ends after consuming available energy Efuel, set \(Lt\approx E_{\rm fuel}\).`,
    String.raw`Divide by positive L to get \(t\approx E_{\rm fuel}/L\). For changing luminosity solve \(\int_0^tL(t')dt'=E_{\rm fuel}\) instead.`),
  'astrophysics-compact-objects': p('Use Einstein’s vacuum equations for a static, spherically symmetric exterior and the asymptotically flat metric ansatz with radial factor f(r).', 'The field equations and symmetry are physical premises. This is a reduced exterior derivation, not a Newtonian escape-speed proof or a rotating-hole solution.',
    String.raw`Write \(ds^2=-f(r)c^2dt^2+f(r)^{-1}dr^2+r^2d\Omega^2\). In vacuum its radial Einstein equation reduces to \(rf'(r)+f(r)-1=0\).`,
    String.raw`Recognize \(d[rf(r)]/dr=1\). Integrate to get \(rf=r+C\), hence \(f=1+C/r\). Matching the weak-field potential Φ=−GM/r fixes \(C=-2GM/c^2\).`,
    String.raw`Therefore \(f(r)=1-2GM/(rc^2)\). The Schwarzschild null horizon is at f=0, giving \(r_s=2GM/c^2\). The coordinate singularity there is removable; the horizon is a causal boundary.`),
  'cosmology-frontiers-expansion': p('In a homogeneous expanding model, physical separation d between comoving objects is scale factor a(t) times their fixed coordinate separation χ.', 'The speed-distance interpretation used in the lesson is local and low-redshift. Large distances require a specified cosmological distance and redshift model.',
    String.raw`Write \(d(t)=a(t)\chi\), with χ fixed for pure expansion and no peculiar motion.`,
    String.raw`Differentiate: \(v=\dot d=\dot a\chi=(\dot a/a)d\). Define the expansion rate \(H=\dot a/a\).`,
    String.raw`At the present epoch H≈H₀, so nearby recession speed is \(v\approx H_0d\). H₀ has inverse-time units, ensuring H₀d has speed units.`),
  'cosmology-frontiers-cosmic-background': p('In homogeneous cosmological expansion, freely propagating photon wavelengths grow with scale factor. The background retains its blackbody spectral shape.', 'This relates the radiation temperature to redshift, not the temperature of every gas cloud. Thermal distortions require separate treatment.',
    String.raw`Redshift is \(1+z=\lambda_0/\lambda=a_0/a\). Frequency and photon energy therefore increase toward the past by the same factor 1+z.`,
    String.raw`A blackbody spectrum depends on the dimensionless ratio \(h\nu/(k_BT)\). Preserving its occupation pattern under ν∝1/a requires T∝1/a.`,
    String.raw`Compare with today: \(T/T_0=a_0/a=1+z\). Thus \(T=T_0(1+z)\).`),
  'cosmology-frontiers-dark-matter-evidence': p('Assume an approximately circular orbit in a spherical Newtonian mass distribution. The shell theorem gives gravity from enclosed mass only.', 'This mass estimator needs geometric and dynamical corrections for real galaxies. A rotation curve alone does not establish a unique microscopic dark-matter model.',
    String.raw`For enclosed mass M(<r), inward gravity on test mass m is \(F_g=GM(<r)m/r^2\). Uniform circular motion requires \(F_c=mv^2/r\).`,
    String.raw`Equate the magnitudes and cancel m: \(GM(<r)/r^2=v^2/r\).`,
    String.raw`Multiply by r² and divide by G to get \(M(<r)=v^2r/G\). A nearly flat v therefore implies enclosed mass continuing to grow roughly in proportion to r.`),
  'cosmology-frontiers-dark-energy-evidence': p('Define an equation-of-state parameter by comparing pressure p with energy density. Here ρ is mass-equivalent density.', 'This is a parameter definition, not proof of a dark-energy mechanism. Its cosmological consequences require Einstein’s equations and a chosen model.',
    String.raw`Mass-energy equivalence makes energy per volume \(u=\rho c^2\). Its units J/m³ are the same as pressure units.`,
    String.raw`Define \(w=p/u\), so \(w=p/(\rho c^2)\) when the energy density is nonzero. Rearranging gives \(p=w\rho c^2\).`,
    String.raw`For an isotropic expanding fluid with constant w, energy conservation gives \(du=-p\,dV\). With V∝a³, integrating yields \(\rho\propto a^{-3(1+w)}\); w=−1 leaves density constant.`),
  'cosmology-frontiers-tested-knowledge-versus-proposals': p('Compare a measured observable O with a model prediction P, using a stated positive uncertainty scale u.', 'A normalized residual is not automatically a discovery significance. Probability claims need an error distribution, correlations, and model-selection controls.',
    String.raw`First compute signed mismatch \(\Delta=O-P\) using the same observable and units.`,
    String.raw`Divide by the uncertainty scale: \(r=\Delta/u=(O-P)/u\). Matching units cancel, leaving a dimensionless residual.`,
    String.raw`A residual of zero means agreement at the central estimate; +2 means O is two uncertainty units above P. Multiplying O, P, and u by the same positive unit-conversion factor leaves r unchanged.`),
};
