import type { DetailedFormulaProof } from './detailed-formula-proofs';
const p = (start: string, limits: string, ...steps: string[]): DetailedFormulaProof => ({ start, limits, steps });

export const foundationProofs: Record<string, DetailedFormulaProof> = {
  'measurement-basics': p('Start with a chosen reference unit and the definition of a physical quantity as a number times that unit.', 'Units define how we report a measurement; they do not prove that a particular object is exactly two meters long.',
    String.raw`Let one reference length be \(u=1\,\mathrm m\). Two consecutive copies have length \(L=u+u=2u=2\,\mathrm m\).`,
    String.raw`Define average speed as distance traveled divided by elapsed time: \(v=d/\Delta t\), with \(\Delta t>0\).`,
    String.raw`The dimension of a quotient is the quotient of dimensions, so \([v]=[d]/[t]=\mathrm m/\mathrm s\).`),
  'unit-conversion': p('Two different unit names can describe the same physical length: one meter equals one hundred centimeters.', 'Exact unit conversions preserve the physical quantity, not the number alone. Measured input precision is unchanged.',
    String.raw`Because \(1\,\mathrm m=100\,\mathrm{cm}\), the ratio \(100\,\mathrm{cm}/(1\,\mathrm m)\) equals one.`,
    String.raw`Multiply by that identity: \(2\,\mathrm m\times100\,\mathrm{cm}/(1\,\mathrm m)\).`,
    String.raw`Cancel the same nonzero meter unit in numerator and denominator. The remaining number is \(2\times100=200\), with unit centimeters.`),
  'measurement-uncertainty': p('An absolute bound means the true value differs from the central estimate by no more than a nonnegative amount u.', 'A bounded interval is not automatically a confidence interval. Relative uncertainty requires a nonzero central magnitude.',
    String.raw`Write the bound as \(|L-L_0|\leq u\). By the definition of absolute value this means \(-u\leq L-L_0\leq u\).`,
    String.raw`Add \(L_0\) to all three parts: \(L_0-u\leq L\leq L_0+u\), which defines the displayed interval.`,
    String.raw`Compare the bound to the positive length scale: \(u/L_0\). A percentage is this dimensionless ratio times 100.`),
  'coordinates-displacement': p('Choose perpendicular coordinate axes and define displacement as the arrow from the initial location to the final location.', 'Both coordinates must use the same frame and units. Displacement is not total path length.',
    String.raw`Reaching the final point requires \(\mathbf r_i+\Delta\mathbf r=\mathbf r_f\). This is the head-to-tail definition of vector addition.`,
    String.raw`Add \(-\mathbf r_i\) to both sides and cancel \(\mathbf r_i-\mathbf r_i=\mathbf0\). Thus \(\Delta\mathbf r=\mathbf r_f-\mathbf r_i\).`,
    String.raw`In two dimensions, subtraction is componentwise: \(\Delta\mathbf r=(x_f-x_i,y_f-y_i)\). Negative components simply mean motion against a positive axis.`),
  'vector-components': p('A vector and its perpendicular projections form a right triangle. Sine and cosine are defined by its side ratios.', 'The angle is measured from the positive x axis. Unit-circle signs extend the triangle relations to all quadrants.',
    String.raw`For magnitude \(A>0\), \(\cos\theta=A_x/A\) and \(\sin\theta=A_y/A\). Multiply by A to obtain both components.`,
    String.raw`Pythagoras gives \(A^2=A_x^2+A_y^2\); alternatively square the projections and use \(\cos^2\theta+\sin^2\theta=1\).`,
    String.raw`Magnitude is nonnegative, so take the positive square root: \(A=\sqrt{A_x^2+A_y^2}\). For the zero vector both components vanish and the direction is undefined.`),
  'vector-addition': p('A displacement can be translated without changing its length or direction. Successive movements add head to tail.', 'This derivation uses ordinary Euclidean coordinates. Vectors must refer to the same axes before their components are added.',
    String.raw`Write \(\mathbf A=A_x\hat{\mathbf x}+A_y\hat{\mathbf y}\) and \(\mathbf B=B_x\hat{\mathbf x}+B_y\hat{\mathbf y}\).`,
    String.raw`Distribute addition and gather the shared basis directions: \(\mathbf A+\mathbf B=(A_x+B_x)\hat{\mathbf x}+(A_y+B_y)\hat{\mathbf y}\).`,
    String.raw`The coefficients of the basis arrows are the resultant coordinates, so \(\mathbf R=(A_x+B_x,A_y+B_y)\). Opposite signed contributions cancel.`),
  'constant-velocity': p('Velocity measures signed position change per time; constant velocity means equal time intervals produce equal displacements.', 'Time intervals must be nonzero. The position equation requires unchanged velocity throughout the modeled interval.',
    String.raw`Between two samples define \(v_x=(x_f-x_i)/(t_f-t_i)\). This is the slope of the straight position-time graph.`,
    String.raw`Choose the initial instant as \(t=0\) and location as \(x_0\). Then \(v_x=(x(t)-x_0)/t\).`,
    String.raw`Multiply by t and add \(x_0\): \(x(t)=x_0+v_xt\). The same equation also holds at t=0 by continuity.`),
  'constant-acceleration': p('Acceleration is the time derivative of velocity and velocity is the time derivative of position. Assume a is constant.', 'These integrations are exact only for constant acceleration. A negative acceleration need not mean the object is slowing down.',
    String.raw`Integrate \(dv/dt=a\) from 0 to t: \(v(t)-v_0=\int_0^t a\,ds=at\), hence \(v=v_0+at\).`,
    String.raw`Integrate position change: \(x(t)-x_0=\int_0^t(v_0+as)\,ds=v_0t+\tfrac12at^2\).`,
    String.raw`The factor one half also follows from the triangular area of height at and base t under the velocity-time graph. Add the rectangle of area \(v_0t\).`),
  'projectile-motion': p('Begin with perpendicular coordinates, Newtonian constant gravity, initial speed v₀ at angle θ, and initial height h. Neglect air drag.', 'The range shortcut assumes equal launch and landing height and a forward nonvertical launch. For other heights use the quadratic root below.',
    String.raw`Right-triangle definitions give \(v_{0x}=v_0\cos\theta\) and \(v_{0y}=v_0\sin\theta\). Gravity has components \(a_x=0\), \(a_y=-g\).`,
    String.raw`Integrate acceleration: \(v_x=v_{0x}\) and \(v_y=v_{0y}-gt\). Integrate again from \((0,h)\): \(x=v_{0x}t\), \(y=h+v_{0y}t-\tfrac12gt^2\).`,
    String.raw`At ground contact set y=0. Rearrange \(gt^2-2v_{0y}t-2h=0\). The nonnegative landing root is \(t_f=(v_{0y}+\sqrt{v_{0y}^2+2gh})/g\).`,
    String.raw`For h=0 and upward launch, the nonzero root reduces to \(t_f=2v_{0y}/g\). Substituting in x gives \(R=2v_0^2\sin\theta\cos\theta/g\).`,
    String.raw`The sine addition identity gives \(\sin(\theta+\theta)=\sin\theta\cos\theta+\cos\theta\sin\theta\). Thus \(R=v_0^2\sin(2\theta)/g\).`),
  'inertia': p('Take Newton’s momentum law as an empirical premise in an inertial frame: net force equals the rate of change of momentum.', 'This is a consequence of an empirical law, not a proof of the law itself. Constant mass and an inertial frame are essential.',
    String.raw`Momentum is \(\mathbf p=m\mathbf v\). With constant mass, \(d\mathbf p/dt=m\,d\mathbf v/dt=m\mathbf a\).`,
    String.raw`If \(\sum\mathbf F=\mathbf0\), the momentum law gives \(m\mathbf a=\mathbf0\). Since m>0, acceleration is zero.`,
    String.raw`Integrating zero acceleration gives \(\mathbf v(t)-\mathbf v(0)=\int_0^t\mathbf0\,ds=\mathbf0\), so velocity remains constant, including rest.`),
  'net-force': p('Draw a free-body diagram on an incline, choose downhill as positive, and use the empirical law ΣF=ma.', 'Include every force component. The displayed simple ramp expression omits friction unless it is separately added.',
    String.raw`Rotate the axes by the incline angle. Gravity projects to downhill \(mg\sin\theta\) and perpendicular \(mg\cos\theta\).`,
    String.raw`The surface constrains perpendicular acceleration to zero, so its normal force balances the perpendicular projection. Along the ramp add the signed applied force: \(F_{\parallel}=F+mg\sin\theta\).`,
    String.raw`Newton’s law along that axis is \(ma=F+mg\sin\theta\). Dividing by positive mass gives \(a=(F+mg\sin\theta)/m\).`),
  'friction': p('Use force balance for the object and the empirical Coulomb friction model. Static friction is an adjustable force, not always its maximum.', 'The coefficients must be measured. Static and kinetic friction are different regimes; these ideal rules do not describe every material or speed.',
    String.raw`With zero acceleration normal to an incline and no extra normal force, \(N-mg\cos\theta=0\), hence \(N=mg\cos\theta\).`,
    String.raw`Let D be the signed downhill drive. Rest requires \(D+f_s=0\), hence \(f_s=-D\). This solution is possible only if \(|D|\leq\mu_sN\).`,
    String.raw`At the threshold \(|D|=\mu_sN\). For gravity alone and \(\cos\theta>0\), divide \(mg\sin\theta\leq\mu_smg\cos\theta\) to get \(\tan\theta\leq\mu_s\).`,
    String.raw`Once sliding, the model assigns opposing magnitude \(f_k=\mu_kN\). Along the ramp its signed contribution is \(-\mu_kN\,\mathrm{sgn}(v)\); net force then sets acceleration.`),
  'work': p('Define incremental work as the force projection along a small displacement: dW=F·dr.', 'Use signed work and a shared frame. The constant-force shortcut does not apply directly to varying forces.',
    String.raw`For a fixed force making angle \(\phi\) with a straight displacement, \(dW=F\cos\phi\,ds\).`,
    String.raw`Integrate the constant projection over length d: \(W=\int_0^d F\cos\phi\,ds=Fd\cos\phi\).`,
    String.raw`Near Earth take vertical position h and downward gravity \(F_h=-mg\). Then \(W_g=\int_{h_i}^{h_f}-mg\,dh=mg(h_i-h_f)\).`),
  'kinetic-energy': p('Use the definition of work and Newton’s law for a point mass, together with the chain rule for derivatives.', 'This is nonrelativistic translational kinetic energy. Rotational or internal energy requires additional terms.',
    String.raw`For one-dimensional motion, \(dW=F\,dx=ma\,dx\). The chain rule gives \(a=dv/dt=(dv/dx)(dx/dt)=v\,dv/dx\).`,
    String.raw`Substitute to obtain \(dW=mv\,dv\). Integrate from initial to final speed: \(W_{\rm net}=m\int_{v_i}^{v_f}v\,dv=\tfrac12m(v_f^2-v_i^2)\).`,
    String.raw`Choose zero energy at rest and identify \(K(v)=\tfrac12mv^2\). Then the integral becomes \(W_{\rm net}=K_f-K_i\).`),
  'energy-conservation': p('Apply the work-energy theorem to a body on a ramp, and include Earth and the heated surfaces in the energy account.', 'The conservation statement is for the whole chosen system. The friction model converts work to one thermal-energy total, not a predicted temperature.',
    String.raw`Conservative gravity permits \(dU=-dW_g=mg\,dh\). Taking U=0 at h=0 gives \(U=mgh\).`,
    String.raw`Kinetic friction along distance s does \(W_f=-\mu mg\cos\theta\,s\). Assign its lost mechanical energy to \(E_{\rm th}=\mu mg\cos\theta\,s\).`,
    String.raw`The work-energy theorem says \(\Delta K=-\Delta U-\Delta E_{\rm th}\). Rearrange to \(\Delta(K+U+E_{\rm th})=0\), so the sum stays at initial value \(E_0\).`),
  'momentum': p('Define momentum p=mv and take Newton’s momentum law plus equal-and-opposite internal forces as the model premises.', 'Conservation requires negligible external impulse. Total momentum can vanish while total kinetic energy remains positive.',
    String.raw`For each cart, \(p_i=m_iv_i\). Define the pair’s momentum \(P=p_1+p_2=m_1v_1+m_2v_2\), using signed velocities.`,
    String.raw`Differentiate: \(dP/dt=F_{12}+F_{21}+F_{\rm external}\). Internal forces cancel because \(F_{12}=-F_{21}\).`,
    String.raw`Thus \(dP/dt=F_{\rm external}\). Integrating over a collision with negligible external impulse yields \(P_f=P_i\).`),
  'impulse': p('A force sustained over time changes momentum according to Newton’s momentum law.', 'An average-force impulse does not determine the peak force. Variable mass requires the momentum form rather than simply mΔv.',
    String.raw`Integrate \(dp/dt=F(t)\) over \([t_i,t_f]\): \(p_f-p_i=\int_{t_i}^{t_f}F(t)\,dt\). Define this signed area as impulse J.`,
    String.raw`Define \(F_{\rm avg}=J/\Delta t\) for \(\Delta t>0\), so \(J=F_{\rm avg}\Delta t\), even when force varies.`,
    String.raw`For unchanged mass, \(p_f-p_i=mv_f-mv_i=m(v_f-v_i)\). Equating the expressions gives the displayed impulse-momentum relation.`),
  'collision-types': p('Work in one dimension with negligible external impulse. Restitution is a measured ratio of relative velocities.', 'The usual 0≤e≤1 range describes passive collisions in this model. The relative approach speed must be nonzero.',
    String.raw`Before contact the approach rate is \(v_{1i}-v_{2i}\); afterward separation is \(v_{2f}-v_{1f}\). Their ratio defines e.`,
    String.raw`For e=0, separation speed is zero, so \(v_{1f}=v_{2f}=v_f\). Momentum conservation gives \(m_1v_{1i}+m_2v_{2i}=(m_1+m_2)v_f\).`,
    String.raw`Divide by \(m_1+m_2>0\): \(v_f=(m_1v_{1i}+m_2v_{2i})/(m_1+m_2)\). Kinetic-energy loss is \(\tfrac12\frac{m_1m_2}{m_1+m_2}(v_{1i}-v_{2i})^2\geq0\).`),
  'circular-motion': p('Parametrize a circle of radius r with a constant angular speed ω, using radians.', 'Acceleration points inward for uniform speed. Changing speed adds tangential acceleration; a centripetal force is the net inward force, not an extra force.',
    String.raw`Position is \(\mathbf r(t)=r(\cos\omega t,\sin\omega t)\). Its derivative is \(\mathbf v=r\omega(-\sin\omega t,\cos\omega t)\).`,
    String.raw`The magnitude is \(v=r\omega\). Differentiate again: \(\mathbf a=-r\omega^2(\cos\omega t,\sin\omega t)\), directed opposite the radius.`,
    String.raw`Its magnitude is \(a_c=r\omega^2=v^2/r\). Newton’s law gives the required inward resultant \(F_c=ma_c=mv^2/r\).`),
  'universal-gravitation': p('Take Newton’s inverse-square attraction as an empirical law for point masses, or spherical masses outside their surfaces.', 'Algebra derives the acceleration from the force law; it does not establish the law experimentally. Strong fields require general relativity.',
    String.raw`The gravitational model states \(\mathbf F=-GMm\,\hat{\mathbf r}/r^2\), where \(\hat{\mathbf r}\) points outward from the source.`,
    String.raw`Insert this force into \(m\mathbf a=\mathbf F\) and divide by positive test mass m: \(\mathbf a=-GM\hat{\mathbf r}/r^2\).`,
    String.raw`Taking magnitudes removes the direction sign and gives \(g(r)=GM/r^2\). The cancellation explains why test masses share acceleration in this model.`),
  'orbits': p('Use Newtonian inverse-square gravity with μ=GM and a fixed source. For eccentricity, assume a purely tangential initial velocity at radius r.', 'The circle formulas describe circular motion only. The eccentricity result assumes a tangential launch; q=0 is a degenerate radial trajectory.',
    String.raw`A circle needs \(v_c^2/r=\mu/r^2\), hence \(v_c=\sqrt{\mu/r}\). One turn covers \(2\pi r\), giving \(T=2\pi\sqrt{r^3/\mu}\).`,
    String.raw`Define specific energy \(\epsilon=v^2/2-\mu/r\) and conserved angular momentum \(\ell=r^2\dot\phi\), which equals rv at a tangential start. The radial equation is \(\ddot r-r\dot\phi^2=-\mu/r^2\).`,
    String.raw`Set u=1/r and use derivatives with respect to φ. Then \(\dot r=-\ell u'\), \(\ddot r=-\ell^2u^2u''\), so the radial equation becomes \(u''+u=\mu/\ell^2\). Its sinusoidal solution gives \(r=\ell^2/[\mu(1+e\cos\phi)]\).`,
    String.raw`Substitute that orbit and its radial velocity in \(\epsilon=(\dot r^2+\ell^2/r^2)/2-\mu/r\): \(\epsilon=\mu^2(e^2-1)/(2\ell^2)\). Thus \(e^2=1+2\epsilon\ell^2/\mu^2\).`,
    String.raw`Write \(q=v/v_c\). Then \(2\epsilon\ell^2/\mu^2=(q^2-2)q^2\), so \(e^2=(q^2-1)^2\) and \(e=|q^2-1|\).`),
  'hookes-law': p('Take a linear restoring spring force F=−kx as an empirical elastic-range approximation, with k>0 and signed displacement x.', 'Hooke’s law is a constitutive model, not a universal theorem. Energy is referenced to the undeformed spring.',
    String.raw`A conservative force satisfies \(F=-dU/dx\). Insert \(-kx\) to get \(dU/dx=kx\).`,
    String.raw`Integrate from the undeformed state: \(U(x)-U(0)=\int_0^x ks\,ds=\tfrac12kx^2\). Choose U(0)=0.`,
    String.raw`For either positive extension or negative compression, \(x^2\geq0\). Differentiating \(\tfrac12kx^2\) returns kx, verifying that its negative derivative is the restoring force.`),
  'spring-period': p('Combine Newton’s law with a linear spring of stiffness k acting on an unchanged mass m, with no damping.', 'The ideal period does not depend on amplitude. Real spring nonlinearity and damping change this result.',
    String.raw`The equation of motion is \(m\ddot x=-kx\), or \(\ddot x+(k/m)x=0\).`,
    String.raw`Try \(x=A\cos(\omega t+\phi)\). Differentiating twice gives \(\ddot x=-\omega^2x\), so the equation is satisfied when \(\omega^2=k/m\).`,
    String.raw`One oscillation advances phase by \(2\pi\): \(\omega T=2\pi\). Hence \(T=2\pi\sqrt{m/k}\), and by definition \(f=1/T\).`),
  'pendulum': p('A point bob on a massless string of fixed length L has tangential displacement Lθ, with θ in radians.', 'The cosine solution and period assume small angles and release from rest. The full nonlinear sine equation has a longer amplitude-dependent period.',
    String.raw`Gravity’s tangential projection is \(-mg\sin\theta\). Newton’s law gives \(mL\ddot\theta=-mg\sin\theta\). Cancel m.`,
    String.raw`The Taylor expansion \(\sin\theta=\theta-\theta^3/6+\cdots\) justifies \(\sin\theta\approx\theta\) near zero. Thus \(\ddot\theta+(g/L)\theta\approx0\).`,
    String.raw`Insert \(\theta=A\cos\omega t+B\sin\omega t\); derivatives give \(\omega^2=g/L\). Release from rest sets B=0 and A=θ₀.`,
    String.raw`The phase repeats after \(\omega T=2\pi\), so \(T\approx2\pi\sqrt{L/g}\) and \(\theta(t)\approx\theta_0\cos(\sqrt{g/L}\,t)\).`),

  'math-arithmetic': p('Natural-number addition counts combined groups. Multiplication abbreviates repeated addition of equal groups.', 'Order of operations is a notation convention; parentheses can specify a different grouping.',
    String.raw`Expand \(3\times4\) as \(4+4+4\). Two groups total eight and the third adds four, giving twelve.`,
    String.raw`The unparenthesized expression \(2+3\times4\) treats that product as a single term, so it becomes \(2+12\).`,
    String.raw`Combining two items with twelve gives fourteen. In contrast \((2+3)\times4\) contains five groups and equals twenty.`),
  'math-signed-numbers': p('Every signed number a has an additive inverse −a such that a+(−a)=0. Subtraction means adding the inverse.', 'Signs describe the chosen direction or quantity. A signed displacement is distinct from a nonnegative distance.',
    String.raw`To find change Δ from initial −2 to final 4, require \(-2+\Delta=4\).`,
    String.raw`Add 2 to both sides and cancel \(-2+2=0\), giving \(\Delta=4+2=6\).`,
    String.raw`Equivalently \(4-(-2)=4+2\), since the inverse of −2 is +2. On the number line this is six units toward the positive direction.`),
  'math-fractions': p('A fraction a/b represents a parts of size 1/b; b must be nonzero. Equal-size parts can be counted together.', 'Multiplying numerator and denominator by the same nonzero number preserves value. Denominator zero is never allowed.',
    String.raw`Each half contains two quarters, so \(1/2=(1\times2)/(2\times2)=2/4\). The multiplying ratio is 2/2=1.`,
    String.raw`Write \(2/4+1/4=(2+1)\times(1/4)\) by factoring the shared part size. This equals \(3/4\).`,
    String.raw`Generally \(a/b+c/d=(ad+bc)/(bd)\), obtained by replacing the first numerator with ad and the second with bc over the same denominator bd.`),
  'math-decimals': p('Base-ten place value assigns successive positions to powers of ten, including negative powers after the decimal point.', 'Finite decimals are exact rational numbers as written; a rounded measurement may still have uncertainty.',
    String.raw`Expand \(0.36=3\times10^{-1}+6\times10^{-2}\). These positions mean tenths and hundredths.`,
    String.raw`Use \(10^{-1}=1/10=10/100\) and \(10^{-2}=1/100\), so \(0.36=30/100+6/100=36/100\).`,
    String.raw`Divide top and bottom by their common factor four to get \(36/100=9/25\). The fraction and decimal name the same value.`),
  'math-ratios': p('Direct proportionality means equal multiplicative changes in x produce equal multiplicative changes in y, with a constant ratio.', 'This rule does not describe an offset relation y=kx+b when b≠0. The ratio itself needs x≠0.',
    String.raw`For x≠0 set the constant ratio \(y/x=k\), where k is fixed for the entire model.`,
    String.raw`Multiply the equality by x and cancel \(x/x=1\). The result is \(y=kx\).`,
    String.raw`Replacing x with cx produces \(y'=k(cx)=c(kx)=cy\). The formula therefore has the defining scaling property, including y=0 at x=0.`),
  'math-scientific-notation': p('A nonnegative integer power counts repeated multiplication. Negative integer powers are reciprocals of positive powers.', 'A normalized scientific-notation coefficient has magnitude from one up to, but not including, ten for a nonzero value.',
    String.raw`For positive exponents, combining the factors in \(10^a10^b\) counts a+b factors, so \(10^a10^b=10^{a+b}\). Reciprocals extend this rule to negative integers.`,
    String.raw`Multiply \((2\times10^3)(3\times10^{-2})\) by grouping coefficients and powers: \((2\times3)10^{3-2}\).`,
    String.raw`This gives \(6\times10^1=60\). If the coefficient had been 60 instead, move one factor of ten to the exponent to normalize it.`),
  'math-powers': p('The square of r is r·r. The symbol √x denotes the nonnegative number whose square is x, for real x≥0.', 'Taking a square root of x² gives |x|, not always x. Negative radicands have no real square root.',
    String.raw`Expand \((2r)^2=(2r)(2r)\) and regroup the real-number factors: \((2\times2)(r\times r)=4r^2\).`,
    String.raw`Both 5 and −5 square to 25, but the principal square-root convention selects the nonnegative root. Thus \(\sqrt{25}=5\).`,
    String.raw`For any real r, \(\sqrt{r^2}=|r|\). Therefore \(\sqrt{4r^2}=2|r|\), which is 2r only when r≥0.`),
  'math-algebra': p('Equality means two expressions have the same value. Applying the same invertible operation preserves their equality.', 'Division by zero is not invertible. Checking by substitution catches arithmetic and sign errors.',
    String.raw`Start from \(2x+3=b\). Add −3 on each side: \((2x+3)-3=b-3\). Associativity cancels 3−3.`,
    String.raw`The remaining equation is \(2x=b-3\). Multiply both sides by 1/2 to get \(x=(b-3)/2\).`,
    String.raw`Substitute back: \(2[(b-3)/2]+3=b-3+3=b\). More generally \(ax+c=b\) gives \(x=(b-c)/a\) provided a≠0.`),
  'math-coordinates': p('An ordered pair fixes a point relative to two axes. A coordinate difference is the change along each axis separately.', 'The axis order matters. Coordinates in different frames must first be transformed to a common frame.',
    String.raw`Write initial point \(\mathbf r_i=(x_i,y_i)\) and final point \(\mathbf r_f=(x_f,y_f)\).`,
    String.raw`Find a displacement \((\Delta x,\Delta y)\) satisfying \((x_i+\Delta x,y_i+\Delta y)=(x_f,y_f)\).`,
    String.raw`Equality of ordered pairs requires equality on both axes: \(\Delta x=x_f-x_i\), \(\Delta y=y_f-y_i\). These are the displayed displacement components.`),
  'math-functions': p('A function is a rule assigning exactly one output to each allowed input. The rule y=2x+1 is an affine example.', 'This is a definition of a particular rule, not a universal relationship between variables.',
    String.raw`Choose an input x and compute its doubled value 2x. Add one afterward to define \(f(x)=2x+1\).`,
    String.raw`For x=3 the operations give \(f(3)=2\times3+1=7\). No second output is allowed for that same input.`,
    String.raw`For two inputs a and b, \(f(b)-f(a)=2b+1-(2a+1)=2(b-a)\). Thus the graph has slope two and crosses y=1 at x=0.`),
  'math-geometry': p('Use Euclidean area and similarity: a right triangle has legs a,b and hypotenuse c; circles of different radii are similar.', 'These are Euclidean plane formulas. The circle-area argument uses the limit of increasingly thin rings.',
    String.raw`Arrange four right triangles inside a square of side a+b with an inner square of side c. Areas give \((a+b)^2=4(ab/2)+c^2\).`,
    String.raw`Expand and cancel 2ab: \(a^2+b^2=c^2\). Similarity makes circumference divided by diameter constant; define that constant as π, giving \(C=2\pi r\).`,
    String.raw`A thin ring of radius s and thickness ds has limiting area \(2\pi s\,ds\). Add all rings: \(A=\int_0^r2\pi s\,ds=\pi r^2\).`),
  'math-trigonometry': p('Similar right triangles with the same angle have equal side ratios. Define cosine and sine from those ratios.', 'Angles in calculus identities must be in radians. The unit circle extends sine and cosine beyond acute angles.',
    String.raw`For a radius r ending at (x,y), the adjacent/hypotenuse ratio is \(\cos\theta=x/r\), and opposite/hypotenuse is \(\sin\theta=y/r\).`,
    String.raw`Multiply by r: \(x=r\cos\theta\), \(y=r\sin\theta\). At r=1 these are the unit-circle coordinates.`,
    String.raw`Substitute into \(x^2+y^2=r^2\) and divide by r² for r≠0: \(\cos^2\theta+\sin^2\theta=1\). Signs follow the quadrant of (x,y).`),
  'math-vectors': p('Represent directed movements in a fixed perpendicular basis. Translating an arrow does not change its components.', 'Component addition describes vectors in one shared basis; magnitudes alone do not generally add.',
    String.raw`An arrow a changes position by \((a_x,a_y)\). Following it with b ends at \((a_x+b_x,a_y+b_y)\) relative to the starting point.`,
    String.raw`Hence \(\mathbf a+\mathbf b=(a_x+b_x,a_y+b_y)\). Swapping order produces the same component sums, establishing commutativity.`,
    String.raw`The resultant magnitude is \(\sqrt{(a_x+b_x)^2+(a_y+b_y)^2}\). It equals the sum of magnitudes only for aligned arrows in the same direction.`),
  'math-rates': p('A straight-line rate compares a change in output with the nonzero change in input over which it occurred.', 'A secant slope is an average rate. An instantaneous rate is the limit as the input interval shrinks.',
    String.raw`Between (x₁,y₁) and (x₂,y₂), define run \(\Delta x=x_2-x_1\) and rise \(\Delta y=y_2-y_1\).`,
    String.raw`A line y=mx+b satisfies \(\Delta y=m\Delta x\). Divide by nonzero Δx to get \(m=\Delta y/\Delta x\).`,
    String.raw`For a curved function, \(f'(x)=\lim_{h\to0}[f(x+h)-f(x)]/h\) when this limit exists. It measures a local rather than whole-interval slope.`),
  'math-accumulation': p('A rate is amount per time. Over a short interval, rate times interval approximates the contributed amount.', 'Signed areas represent signed accumulation. An integral is exact when the limiting sum exists, rather than a finite coarse rectangle sum.',
    String.raw`For constant rate v over duration Δt, every interval contributes proportionally, so \(\Delta x=v\Delta t\). Geometrically this is a rectangle’s area.`,
    String.raw`Partition variable motion into intervals and use \(\Delta x\approx\sum_i v(t_i)\Delta t_i\). Smaller intervals better track a changing rate.`,
    String.raw`As maximum interval width tends to zero, the sum defines \(\Delta x=\int_{t_0}^{t_1}v(t)\,dt\). Negative rate contributes negative signed area.`),
  'math-sine': p('The unit-circle vertical coordinate is sin φ. A rotating phase sweeps angular distance ωt at constant angular frequency ω.', 'This is a sinusoidal model. Period needs ω>0 as written; for signed angular rate use its magnitude.',
    String.raw`An initial phase φ becomes \(\omega t+\phi\). Scaling the unit-circle height by A gives \(y=A\sin(\omega t+\phi)\).`,
    String.raw`One turn is 2π radians and returns to the same point, so \(\sin(u+2\pi)=\sin u\). A full repeat therefore requires \(\omega T=2\pi\).`,
    String.raw`Divide by ω to get \(T=2\pi/\omega\). Frequency is \(f=1/T=\omega/(2\pi)\); amplitude sets height, not the repeat time.`),
  'math-uncertainty': p('A statement x±u means a central estimate x with an absolute nonnegative bound u, in the same units.', 'A relative percentage requires x≠0 and compares with |x|. This bound alone specifies neither a probability nor a confidence level.',
    String.raw`If the true value X satisfies \(|X-x|\leq u\), the absolute-value inequality is \(-u\leq X-x\leq u\).`,
    String.raw`Add x to obtain \(x-u\leq X\leq x+u\). The interval width is \((x+u)-(x-u)=2u\).`,
    String.raw`The central magnitude is |x|, so relative bound is \(u_r=u/|x|\), and percent bound is \(100u/|x|\). Matching units cancel in the ratio.`),
};
