/** A physical law is an experimentally supported premise, not an algebraic theorem.
 * Each entry names that premise and then shows the mathematical deduction used by
 * the displayed classroom formula. Definitions are identified as definitions. */
import { starterFormulaReasoning } from './starter-formula-reasoning';

export interface FormulaReasoning {
  basis: string;
  steps: readonly string[];
  help?: string;
}

const r = (basis: string, first: string, second: string, help?: string): FormulaReasoning => ({ basis, steps: [first, second], help });

export const formulaReasoning: Record<string, FormulaReasoning> = {
  'measurement-basics': r('A measurement is a number together with a unit; a unit equation states the dimensions assigned to a quantity.', 'The example length is two copies of the meter, so its measured value is 2 m.', 'Speed is length divided by time, so its SI unit is m divided by s. This is a dimensional definition.'),
  'unit-conversion': r('One meter and 100 centimeters name the same length, so their ratio is exactly one.', 'Multiply 2 m by (100 cm)/(1 m); multiplying by one preserves the physical length.', 'Cancel the meter units and multiply 2 by 100 to obtain 200 cm.'),
  'measurement-uncertainty': r('Here u is a stated absolute bound around a nonzero central measurement L₀; it is not automatically a statistical standard deviation.', 'Subtract and add u to L₀ to form the lower and upper bounds of the interval.', 'Divide u by L₀ to compare the bound with the measured scale, then multiply by 100 to express a percent.', 'If the central value is zero, a relative percentage is undefined; use the absolute uncertainty.'),
  'coordinates-displacement': r('Displacement means the change from an initial position vector to a final position vector.', 'Start at rᵢ and add the displacement Δr to arrive at rᶠ.', 'Subtract rᵢ from both sides: Δr = rᶠ − rᵢ. Subtract each coordinate separately.'),
  'vector-components': r('Resolve a vector of magnitude A into perpendicular horizontal and vertical legs at angle θ from +x.', 'The cosine and sine definitions give cos θ = Aₓ/A and sin θ = Aᵧ/A, so multiply by A for each component.', 'The legs form a right triangle; Pythagoras gives A² = Aₓ² + Aᵧ², hence the nonnegative square root gives A.', 'Sine and cosine are side ratios; the unit circle supplies correct signs outside the first quadrant.'),
  'vector-addition': r('An arrow is unchanged by translation; following A and then B leads to the same endpoint as the resultant R.', 'The horizontal displacement is Aₓ followed by Bₓ, so Rₓ = Aₓ + Bₓ.', 'The vertical displacement is Aᵧ followed by Bᵧ, so Rᵧ = Aᵧ + Bᵧ. Together these define R.'),
  'constant-velocity': r('Average velocity is defined as position change per elapsed time; assume it is constant over the interval.', 'Subtract the initial from the final coordinate and divide by tᶠ − tᵢ to obtain vₓ.', 'With t measured from the initial instant, multiply vₓ by t for the displacement and add x₀ for position.'),
  'constant-acceleration': r('Acceleration is velocity change per time; these kinematic equations assume that acceleration is constant.', 'From a = (v − v₀)/t, multiply by t and add v₀: v = v₀ + at.', 'Average velocity is (v₀ + v)/2 under constant acceleration. Multiply by t and substitute v = v₀ + at to obtain Δx = v₀t + ½at².', 'Average velocity equals the midpoint value only when velocity changes linearly in time; the velocity–time graph is a trapezoid.'),
  'projectile-motion': {
    basis: 'Assume flat ground, no air resistance, constant downward gravity g, horizontal launch origin x₀ = 0, and initial height h.',
    steps: [
      String.raw`Draw a right triangle for launch speed. Trigonometry gives horizontal velocity \(v_{0x}=v_0\cos\theta\) and initial vertical velocity \(v_{0y}=v_0\sin\theta\).`,
      String.raw`Horizontal acceleration is zero, so \(x(t)=v_{0x}t=v_0\cos\theta\,t\). Vertical acceleration is \(-g\), so constant-acceleration motion gives \(y(t)=h+v_0\sin\theta\,t-\tfrac12gt^2\).`,
      String.raw`Only for equal launch and landing height, set \(h=0\) and \(y=0\). Factor \(0=t(v_0\sin\theta-\tfrac12gt)\). Ignoring the launch-time root \(t=0\), flight time is \(t_{\rm flight}=2v_0\sin\theta/g\).`,
      String.raw`Range is horizontal velocity times flight time: \(R=(v_0\cos\theta)(2v_0\sin\theta/g)=2v_0^2\sin\theta\cos\theta/g\). Since \(\sin(2\theta)=2\sin\theta\cos\theta\), this becomes the displayed range expression.`,
    ],
    help: 'Sine and cosine are side ratios of a right triangle: sin θ gives the vertical share of launch speed and cos θ gives the horizontal share. Constant acceleration adds a velocity change of −gt each second, so vertical position includes −½gt². Setting landing height to zero produces two times: launch at t = 0 and landing at the later root. Finally sin(2θ) = 2 sin θ cos θ combines the flight-time and horizontal-speed factors. For h ≠ 0, solve the full quadratic landing equation instead.',
  },
  'inertia': r('Newton’s first and second laws are empirical premises in an inertial frame: net force changes momentum or velocity.', 'For fixed mass, Newton’s second law gives a = ΣF/m; if ΣF = 0, acceleration is zero.', 'Zero acceleration means velocity has no change with time, so the velocity vector remains constant.'),
  'net-force': r('Use Newton’s second law for a fixed mass and resolve every applied force along the chosen ramp axis.', 'Gravity’s component along the ramp is mg sin θ; add the signed applied force F to obtain F∥.', 'Set the net force equal to ma and divide by m to obtain the acceleration. Keep force directions signed.', 'Sine gives the side of the gravity vector parallel to the ramp; a free-body diagram fixes its sign.'),
  'friction': r('The friction coefficients are empirical material-model parameters; the static bound and kinetic rule are model premises.', 'Resolve gravity perpendicular to the ramp to obtain N = mg cos θ when no other force has a normal component.', 'Static friction adjusts as needed up to μₛN; once sliding, the model uses kinetic magnitude μₖN opposite motion.'),
  'work': r('Work is defined as the force component along displacement accumulated over the motion.', 'For a constant force, the parallel component is F cos φ; multiply by path length d to obtain W.', 'Near Earth, gravity’s vertical component is mg, so its work equals mg times the height lost, hᵢ − hᶠ.', 'For varying forces, add small contributions F∥ Δs and take the limiting area under the force–distance graph.'),
  'kinetic-energy': r('Use Newton’s second law and the definition of work for a fixed-mass body; take zero kinetic energy at zero speed.', 'For motion along the force, W = Fd = mad. Constant-acceleration kinematics gives 2ad = vᶠ² − vᵢ².', 'Substitute ad = (vᶠ² − vᵢ²)/2: W = ½mvᶠ² − ½mvᵢ². This identifies K = ½mv².'),
  'energy-conservation': r('Assume energy conservation for the chosen body–Earth–surfaces system and the stated constant-friction ramp model.', 'Gravity changes potential by ΔU = mg Δh; choose the ramp bottom as U = 0 to obtain U = mgh.', 'Friction does work of magnitude μmg cos θ·s, recorded as thermal gain. Add K, U and thermal energy to keep the initial total E₀.', 'Conservation applies to the whole defined system; mechanical energy alone falls when friction heats the surfaces.'),
  'momentum': r('Momentum is defined as mass times velocity; Newton’s second law says net impulse changes total momentum.', 'For one cart, multiply its signed velocity by mass to obtain p = mv.', 'Add both cart momenta componentwise to obtain system P. Equal and opposite internal impulses cancel, so P stays fixed without external impulse.'),
  'impulse': r('Impulse is the time accumulation of force; Newton’s second law relates it to a change in momentum.', 'For a constant or average force over Δt, the force–time area is J = Favg Δt.', 'For fixed mass, Δp = mvᶠ − mvᵢ = m(vᶠ − vᵢ). Equating impulse and momentum change gives the relation.'),
  'collision-types': r('Restitution is defined as separation speed divided by approach speed; total momentum is conserved only for negligible external impulse.', 'Take the relative speed after contact, v₂ᶠ − v₁ᶠ, over the relative approach speed, v₁ᵢ − v₂ᵢ, to define e.', 'When e = 0 the carts share vᶠ. Set initial momentum equal to (m₁ + m₂)vᶠ and divide by the total mass.'),
  'circular-motion': r('For uniform circular motion, geometry gives inward acceleration magnitude v²/r; Newton’s second law connects it to net force.', 'Over a short turn Δθ, velocity changes direction by Δv ≈ vΔθ. Since arc distance vΔt = rΔθ, Δθ/Δt = v/r.', 'Divide Δv by Δt and take the small-angle limit to get a inward = v²/r. Multiply by m for the required inward net force.', 'Small-angle geometry uses the fact that a chord approaches its arc as the angle tends to zero.'),
  'universal-gravitation': r('The inverse-square gravitational force is an experimentally supported Newtonian law, not a result proved by algebra.', 'Insert masses M and m and center separation r into the force law to get force magnitude GMm/r².', 'Divide by the test mass m in F = ma; m cancels and gives gravitational acceleration g(r) = GM/r².'),
  'orbits': r('Assume Newtonian gravity, a fixed central mass, a circular orbit for v꜀ and T, and a tangential launch for the eccentricity relation.', 'Set GM/r² = v꜀²/r and solve for v꜀; circumference 2πr divided by v꜀ gives T = 2π√(r³/GM).', 'For a tangential start, use orbital energy and angular momentum: e² = 1 + (q² − 2)q² = (q² − 1)², so e = |q² − 1|.', 'The eccentricity step uses conserved specific energy ε = v²/2 − GM/r and specific angular momentum ℓ = rv; it does not apply to arbitrary launch directions.'),
  'hookes-law': r('Hooke’s linear restoring-force law F = −kx is an empirical approximation within a spring’s elastic range.', 'The negative sign makes the force oppose signed displacement x.', 'Work against the spring rises linearly from zero to kx; the triangular force–displacement area is ½·x·kx = ½kx².'),
  'spring-period': r('Assume a linear Hooke spring, constant mass, and no damping; solve Newton’s second law for the resulting motion.', 'From m x″ = −kx, try x = A cos(ωt). Since x″ = −ω²x, comparison gives ω² = k/m.', 'A cosine repeats after phase 2π, so T = 2π/ω = 2π√(m/k). Frequency counts cycles per second: f = 1/T.', 'A second derivative is the rate of change of velocity; differentiating cosine twice returns negative cosine.'),
  'pendulum': r('Assume a point bob, massless string, no drag, and small angular displacement θ measured in radians.', 'Tangential gravity gives mL θ″ = −mg sin θ. For small θ, sin θ ≈ θ, so θ″ = −(g/L)θ.', 'The same cosine solution as a spring has ω = √(g/L), hence θ(t) ≈ θ₀ cos(ωt) when released from rest and T ≈ 2π√(L/g).', 'The approximation sin θ ≈ θ is accurate near zero radians. Finite-amplitude pendulums take slightly longer.'),

  'math-arithmetic': r('Multiplication is repeated equal grouping; the conventional order of operations makes the expression unambiguous.', 'Three groups of four contain 3 × 4 = 12 items.', 'Add the remaining two items to the groups: 2 + 12 = 14.'),
  'math-signed-numbers': r('A signed change is defined as final value minus initial value.', 'Write the final coordinate 4 and subtract the initial coordinate −2.', 'Subtracting −2 is adding 2, so the signed change is +6.'),
  'math-fractions': r('Fractions add directly only when their parts use the same-sized denominator.', 'Rewrite one half as two quarters by multiplying top and bottom by two.', 'Add two quarters and one quarter to obtain three quarters.'),
  'math-decimals': r('Decimal place value defines each digit after the point as tenths, hundredths, and so on.', 'The 3 in 0.36 means three tenths; the 6 means six hundredths.', 'Three tenths is 30 hundredths; add six to obtain 36/100.'),
  'math-ratios': r('Direct proportionality means that y/x has the same value k for every nonzero x.', 'Start with y/x = k and multiply both sides by x.', 'The multiplication gives y = kx; dividing back by x recovers k.'),
  'math-scientific-notation': r('Powers of ten follow the exponent rule 10ᵃ·10ᵇ = 10ᵃ⁺ᵇ.', 'Multiply coefficients 2 × 3 = 6 and add exponents 3 + (−2) = 1.', 'The product is 6 × 10¹, or 60.'),
  'math-powers': r('Squaring means multiplying a number by itself; the nonnegative square root undoes that operation.', 'Expand (2r)² as (2r)(2r) = 4r².', 'Because 5² = 25 and 5 is nonnegative, √25 = 5.'),
  'math-algebra': r('An equality remains true when the same reversible operation is applied to both sides.', 'Subtract 3 from both sides of 2x + 3 = b to obtain 2x = b − 3.', 'Divide both sides by the nonzero coefficient 2 to obtain x = (b − 3)/2.'),
  'math-coordinates': r('A vector change is final position minus initial position, independently on each perpendicular axis.', 'Subtract initial x from final x for the horizontal change.', 'Subtract initial y from final y for the vertical change, giving the ordered pair.'),
  'math-functions': r('The formula defines a rule that assigns exactly one output y to every allowed input x.', 'First multiply the chosen input x by two.', 'Then add one; for example x = 3 produces y = 7.'),
  'math-geometry': r('Use Euclidean right-triangle geometry and the definitions of π, circle circumference, and area.', 'Four copies of a right triangle fit in a square of side a + b; comparing the leftover areas gives a² + b² = c².', 'π is circumference divided by diameter, giving C = 2πr. Summing thin circular rings of circumference 2πr gives area πr².', 'The ring argument uses accumulation: each thin ring contributes its circumference multiplied by its thickness.'),
  'math-trigonometry': r('Sine and cosine are defined as opposite/hypotenuse and adjacent/hypotenuse in a right triangle.', 'For a vector of length r, cos θ = x/r and sin θ = y/r.', 'Multiply each equality by r to isolate x and y; extend signs to all quadrants with the unit circle.'),
  'math-vectors': r('Vector addition joins displacements head to tail and does not depend on where the arrows are drawn.', 'The first arrow moves horizontally by aₓ and the second by bₓ, giving aₓ + bₓ.', 'The same argument vertically gives aᵧ + bᵧ, so the resultant is the pair of component sums.'),
  'math-rates': r('Slope is defined as vertical change divided by horizontal change between two distinct input points.', 'Find the rise by subtracting y₁ from y₂.', 'Find the run by subtracting x₁ from x₂; divide rise by run when the run is nonzero.'),
  'math-accumulation': r('Accumulation adds each small amount contributed by a rate during its time interval.', 'For a constant rate v over Δt, the rectangular area is vΔt.', 'For changing v, split time into intervals, multiply each vᵢ by Δtᵢ, and add; the sum approaches exact displacement as widths shrink.', 'This is the idea behind an integral: the limit of increasingly fine signed-area sums.'),
  'math-sine': r('Sine repeats when its angle increases by 2π radians; angular frequency ω measures angle advanced per second.', 'At time t the phase is ωt + φ, and multiplying its sine by A sets the amplitude.', 'A full cycle adds 2π to phase: ωT = 2π, so T = 2π/ω when ω > 0.'),
  'math-uncertainty': r('Interpret x ± u as a stated bounded interval with u ≥ 0, and x ≠ 0 for relative percent uncertainty.', 'Subtract and add u to get the lower and upper interval endpoints.', 'Divide u by |x| and multiply by 100 to express the bound as a percentage of the central magnitude.'),
  ...starterFormulaReasoning,
};
