import type { FormulaReasoning } from './formula-reasoning';

const r = (basis: string, first: string, second: string, help?: string): FormulaReasoning => ({ basis, steps: [first, second], help });

/** Authored deductions for every five-mission starter course. */
export const starterFormulaReasoning: Record<string, FormulaReasoning> = {
  'classical-mechanics-frames-and-motion': r('Choose a frame moving at constant velocity u relative to the original frame; this is a Galilean, low-speed transformation.', 'In time t the moving origin shifts by ut, so its coordinate for the object is x′ = x − ut.', 'Divide the change in x′ by the same elapsed time: v′ = v − u.'),
  'classical-mechanics-force-diagrams': r('Newton’s second law is an experimentally supported rule for the net force on a fixed mass in an inertial frame.', 'Resolve and sum all forces along the chosen axis to obtain Fnet.', 'From Fnet = ma, divide both sides by nonzero m to obtain a = Fnet/m.'),
  'classical-mechanics-rotation': r('Torque magnitude is the turning effect of a force about a pivot, defined by the perpendicular lever arm.', 'Resolve F into its perpendicular component F⊥ relative to the radius from pivot to contact point.', 'The turning magnitude is lever arm r times that component, τ = rF⊥. Its sign depends on clockwise or counterclockwise sense.', 'For a force at angle φ to the radius, F⊥ = F sin φ.'),
  'classical-mechanics-fluids-and-pressure': r('For a resting fluid of nearly constant density, force balance on a thin horizontal slab relates pressure change to its weight.', 'A slab of area A and height h has mass ρAh and weight ρAhg.', 'The pressure force difference is ΔP·A; equate it to the weight and cancel A to get ΔP = ρgh.'),
  'classical-mechanics-chaos-and-limits': r('This is a toy doubling map for separation; real chaotic systems do not generally double every step.', 'If each step doubles the previous separation, d₁ = 2d₀ and d₂ = 2(2d₀) = 2²d₀.', 'Repeating the same multiplication n times gives dₙ = 2ⁿd₀ by induction.', 'Exponential growth applies only while separations remain inside the model’s local range.'),

  'waves-sound-oscillation': r('Frequency f counts cycles per second; period T is seconds per cycle for a repeating motion.', 'In time t, the count is N = ft, so one cycle takes t = 1/f.', 'That one-cycle duration is the period T, giving T = 1/f for f > 0.'),
  'waves-sound-traveling-waves': r('A repeating wave advances one wavelength λ in one period T through a uniform medium.', 'Speed is distance divided by time, so v = λ/T.', 'Because f = 1/T, substitute to obtain v = fλ.'),
  'waves-sound-superposition': r('Linear superposition is a model premise: independent small-amplitude disturbances add at the same position and time.', 'Evaluate each disturbance y₁ and y₂ using the same position, time, and sign convention.', 'Add the signed displacements to obtain y = y₁ + y₂; opposite signs can cancel.'),
  'waves-sound-resonance': r('For the fundamental standing wave on a string fixed at both ends, nodes at the ends enclose half a wavelength.', 'The length is L = λ₁/2, so λ₁ = 2L.', 'Use wave speed v = fλ to solve f₁ = v/(2L).', 'Different boundary conditions, such as an open pipe, can have a different fundamental pattern.'),
  'waves-sound-sound-and-spectra': r('The decibel scale is a logarithmic definition for an intensity ratio relative to reference I₀.', 'Form the dimensionless ratio I/I₀; equal intensities give ratio one.', 'Take base-10 logarithm and multiply by 10 for intensity level β. Tenfold intensity gives +10 dB.', 'A logarithm asks what power of ten produces a positive ratio; zero or negative intensity is outside this definition.'),

  'thermodynamics-microscopic-temperature': r('Equipartition is a classical equilibrium result for quadratic motion, applicable in its stated temperature regime.', 'Each of three independent translational directions contributes average energy ½kBT.', 'Add the three contributions to obtain average translational kinetic energy 3kBT/2.', 'Quantum effects can invalidate classical equipartition at low temperatures.'),
  'thermodynamics-ideal-gas': r('The ideal-gas law PV = nRT is an empirical/statistical model for a dilute gas at equilibrium.', 'Keep amount n and temperature T fixed; multiply them with gas constant R to obtain PV.', 'Divide both sides by nonzero volume V to obtain P = nRT/V.'),
  'thermodynamics-first-law': r('The first law is energy conservation for a defined system; use the sign convention that W is work done by the system.', 'Heat Q adds energy to the system while work W transfers energy out.', 'Add signed transfers: final minus initial internal energy is ΔU = Q − W.'),
  'thermodynamics-entropy': r('For a reversible transfer at constant absolute temperature T, entropy change is defined through reversible heat divided by T.', 'Split the heat into small reversible transfers δQrev; each contributes δS = δQrev/T.', 'If T stays constant, sum the transfers and take 1/T outside the sum to obtain ΔS = Qrev/T.', 'For changing temperature, use an integral of δQrev/T; irreversible heat transfer needs a reversible comparison path.'),
  'thermodynamics-engines-and-limits': r('A reversible heat engine has zero total entropy change for its two reservoirs; real engines perform no better.', 'Entropy balance gives Qh/Th = Qc/Tc, so Qc/Qh = Tc/Th.', 'Efficiency is useful work divided by heat input: η = (Qh − Qc)/Qh = 1 − Tc/Th.'),

  'electromagnetism-charge-and-field': r('Coulomb’s inverse-square force is an experimentally supported electrostatic law for point charges.', 'A test charge qₜ at distance r feels radial force Fᵣ = kq qₜ/r² from source charge q.', 'Electric field is force per test charge, Eᵣ = Fᵣ/qₜ; cancel qₜ to obtain kq/r².'),
  'electromagnetism-potential': r('Use Coulomb’s field and define potential difference as work per unit charge, with zero potential at infinity.', 'Moving radially through Eᵣ = kq/r² gives a potential change from infinity of the accumulated inverse-square field.', 'The accumulated radial area is kq/r, so V(r) = kq/r with the source-charge sign.', 'The accumulation uses an integral: the antiderivative of 1/r² is −1/r.'),
  'electromagnetism-current': r('Average electric current is defined as charge crossing a chosen surface per elapsed time.', 'Measure the charge ΔQ crossing during a nonzero interval Δt.', 'Divide charge by time to obtain I = ΔQ/Δt; its unit is C/s, called the ampere.'),
  'electromagnetism-magnetic-force': r('The Lorentz magnetic-force law is an empirical premise; this displayed magnitude assumes velocity perpendicular to field.', 'General magnitude is |q|vB sin φ, where φ is the velocity–field angle.', 'At φ = 90°, sin φ = 1, so F = |q|vB. Direction comes from the cross product.', 'At parallel alignment, sin φ = 0 and the magnetic force vanishes.'),
  'electromagnetism-maxwells-synthesis': r('This relation is a property of a plane electromagnetic wave in vacuum derived from Maxwell’s vacuum equations.', 'The coupled electric and magnetic wave equations propagate at c = 1/√(μ₀ε₀).', 'For the same plane wave, the field-amplitude relation is E/B = c; multiply by B to get E = cB.', 'A static point-charge field is not a traveling plane wave, so this ratio does not describe every electromagnetic field.'),

  'electronics-voltage-current-resistance': r('Ohm’s law V = IR is an empirical linear approximation for an ohmic resistor at fixed conditions.', 'Potential difference across the resistor equals current times resistance.', 'Divide V = IR by nonzero R to obtain I = V/R; volts per ohm are amperes.'),
  'electronics-schematics-and-breadboards': r('Energy conservation around a simple closed circuit loop makes the net signed potential change zero.', 'Start at the source: it raises potential by Vs; two resistor drops lower it by VR₁ and VR₂.', 'Write Vs − VR₁ − VR₂ = 0 and rearrange to obtain Vs = VR₁ + VR₂.'),
  'electronics-series-and-parallel': r('Parallel resistors have the same voltage and their branch currents add at a junction.', 'Ohm’s law gives I₁ = V/R₁ and I₂ = V/R₂, so Itotal = V(1/R₁ + 1/R₂).', 'Define Req by Itotal = V/Req; divide by V to obtain 1/Req = 1/R₁ + 1/R₂.'),
  'electronics-led-and-polarity': r('Use a constant forward LED voltage-drop approximation and Ohm’s law for its series resistor.', 'Loop balance leaves VR = Vs − VLED across the resistor when the LED conducts.', 'Ohm’s law gives I = VR/R = (Vs − VLED)/R; the simple model clips negative results to zero.', 'A real LED has a nonlinear current–voltage curve, and a board pin has a current limit.'),
  'electronics-power-and-measurement': r('Power is transferred energy per time; voltage is transferred energy per charge.', 'Multiply energy per charge V = ΔE/ΔQ by charge per time I = ΔQ/Δt.', 'Charge cancels, leaving P = ΔE/Δt = VI for the same component and time interval.'),

  'arduino-esp32-board-and-safe-wiring': r('Treat the output pin as an approximate voltage source and the LED as an assumed fixed drop in a series loop.', 'The voltage left across the resistor is Vpin − VLED.', 'Divide by the resistor value R using Ohm’s law to estimate LED current; obey the pin current limit.'),
  'arduino-esp32-blink-sketch': r('Blink frequency is cycles per second, while period T is seconds for one complete HIGH-plus-LOW cycle.', 'Over one cycle the cycle count is one and elapsed time is T.', 'Divide one cycle by T seconds to obtain f = 1/T for T > 0.'),
  'arduino-esp32-button-input': r('This is an active-high digital encoding choice, not a physical law; pull-up wiring would reverse the states.', 'Assign code 1 when the sampled button signal is HIGH in the pressed state.', 'Assign code 0 when the signal is LOW in the released state; these two cases define x.'),
  'arduino-esp32-pwm-output': r('Duty fraction is defined as the part of each PWM cycle for which the output is HIGH.', 'One full PWM cycle lasts T and contains tHIGH seconds in the HIGH state.', 'Divide the HIGH duration by the total duration to obtain D = tHIGH/T, with 0 ≤ D ≤ 1.'),
  'arduino-esp32-analog-sensor': r('Assume an ideal b-bit uniform ADC whose input range 0 to Vref maps to integer codes 0 through 2ᵇ − 1.', 'Normalize the allowed voltage: Vin/Vref is its fraction of full scale.', 'Multiply by the largest code 2ᵇ − 1, then round to the nearest integer; clamp out-of-range inputs.', 'The approximation ignores quantization convention, reference error, noise, and board-specific nonlinearities.'),

  'optics-reflection': r('Specular reflection follows the equal-angle rule for a smooth surface; it can also be deduced from equal-speed shortest-time paths.', 'Reflect the destination point across a flat mirror. The shortest straight path to that reflected point crosses the mirror at the reflection point.', 'The two right triangles at that crossing have equal geometric angles, so incidence and reflection angles relative to the normal match.'),
  'optics-refraction': r('At a stationary boundary, the wave phase must agree along the interface; wave speed changes between media.', 'A phase front travels distances v₁t and v₂t in equal time on the two sides, giving sin θ₁/sin θ₂ = v₁/v₂.', 'Use refractive index n = c/v and rearrange to obtain n₁ sin θ₁ = n₂ sin θ₂.', 'A wavefront is a line of equal phase; matching it along the boundary keeps crests continuous.'),
  'optics-lenses': r('Start from the thin-lens equation 1/f = 1/dₒ + 1/dᵢ, valid in the paraxial approximation.', 'Subtract 1/dₒ from both sides while keeping object and image distances signed consistently.', 'The result is 1/dᵢ = 1/f − 1/dₒ. Invert only after checking that the right side is nonzero.', 'The thin-lens equation follows from similar triangles for rays near the optical axis; it does not model diffraction or thick lenses.'),
  'optics-interference': r('Coherent waves interfere constructively when their phase difference is an integer number of full cycles.', 'Traveling one extra wavelength advances phase by one full 2π turn.', 'Thus m extra wavelengths give path difference ΔL = mλ for integer m.'),
  'optics-photons-and-imaging': r('Planck’s photon-energy relation E = hf is an experimentally supported quantum premise, not derivable from classical wave geometry alone.', 'Frequency f counts oscillations each second; Planck’s constant h has energy·time units.', 'Multiply h by f to obtain photon energy, and verify the units reduce to joules.'),

  'relativity-events-and-frames': r('β is a definition: speed compared with invariant vacuum light speed c.', 'Take the object speed v and the positive reference speed c in the same units.', 'Divide v by c; units cancel, and massive objects in an inertial frame have 0 ≤ β < 1.'),
  'relativity-light-clock-dilation': r('Assume the same vacuum light speed c in every inertial frame and a light clock moving sideways at speed v.', 'During half a tick, the light path forms a right triangle: (ct/2)² = (ct₀/2)² + (vt/2)².', 'Rearrange to t²(1 − v²/c²) = t₀², so t/t₀ = 1/√(1 − β²), called γ.', 't₀ is the clock’s proper time between its own ticks; the path is longer in the frame where the clock moves.'),
  'relativity-length-and-simultaneity': r('Lorentz transformations preserve c and connect positions measured in different inertial frames; length must use simultaneous endpoint measurements.', 'For a rod at rest in its own frame, subtract transformed endpoint coordinates at the same lab time.', 'The result is L = L₀/γ along the motion direction, with γ from light-clock dilation.', 'Simultaneous in one frame is not generally simultaneous in another; that condition is essential in a length measurement.'),
  'relativity-energy-momentum': r('Relativistic energy is defined by the Lorentz-invariant energy–momentum relation and the low-speed energy limit.', 'For a particle of rest mass m and speed v, relativistic momentum is p = γmv.', 'Solve E² = (pc)² + (mc²)² for positive E; substituting p and γ gives E = γmc².', 'This includes rest energy mc²; kinetic energy is (γ − 1)mc².'),
  'relativity-curved-spacetime': r('In a weak approximately uniform gravitational field, the equivalence principle predicts a small clock-rate difference over height h.', 'A gravitational potential difference is approximately ΔΦ = gh.', 'For |ΔΦ| much smaller than c², fractional clock-rate difference is δ ≈ ΔΦ/c² = gh/c².', 'This is a weak-field approximation, not a derivation of the full Einstein field equations.'),

  'quantum-light-quanta': r('Photon energy E = hf is an experimentally supported quantum postulate, not a theorem of classical mechanics.', 'Frequency f counts field oscillations per second and h sets the energy scale per cycle rate.', 'Multiply h by f to obtain energy in joules; doubling frequency doubles the photon energy.'),
  'quantum-build-a-wavefunction': r('The Born rule is a quantum postulate: squared wavefunction magnitude gives probability density in position.', 'Write a complex amplitude ψ = a + ib; its squared magnitude is ψ*ψ = a² + b², which is nonnegative.', 'Identify that magnitude with density ρ(x) after normalizing the total area under ρ to one.', 'Complex amplitudes can interfere before squaring; probabilities themselves are nonnegative.'),
  'quantum-measurement-probabilities': r('The outcomes i are mutually exclusive and have normalized probabilities pᵢ.', 'An event A happens if any one of its listed outcomes occurs.', 'Add the probabilities of those disjoint outcomes to obtain P(A) = Σ over i in A of pᵢ.'),
  'quantum-uncertainty': r('The position–momentum uncertainty bound follows from wavefunction Fourier mathematics and the quantum relation p = ℏk.', 'For normalized wave amplitudes, the Fourier spread theorem gives Δx·Δk ≥ 1/2.', 'Multiply by ℏ and use Δp = ℏΔk to obtain Δx·Δp ≥ ℏ/2.', 'This is a property of state spreads, not a claim that a measuring instrument necessarily disturbs the particle.'),
  'quantum-tunneling': r('For a one-dimensional rectangular barrier with energy below barrier height, the Schrödinger equation gives an evanescent amplitude inside.', 'Inside the barrier the amplitude falls approximately as exp(−κx), so crossing thickness a reduces amplitude by exp(−κa).', 'Probability is amplitude magnitude squared, giving transmission scale exp(−2κa); boundary matching adds a prefactor.', 'The displayed expression is a thick-barrier approximation, not an exact transmission probability for every energy.'),

  'atomic-molecular-spectra': r('Energy conservation and the photon relation connect a downward atomic transition to emitted light.', 'An atom drops from initial energy Eᵢ to lower energy Eᶠ; energy released is Eᵢ − Eᶠ.', 'Assign the released energy to one emitted photon to obtain Eγ = Eᵢ − Eᶠ.'),
  'atomic-molecular-bohr-scale': r('The 1/n² level pattern is a hydrogen-model result from an inverse-square Coulomb potential and allowed stationary states.', 'In the Bohr model, angular momentum condition mvr = nℏ and force balance mv²/r = ke²/r² imply radius scales as n².', 'Insert that radius into kinetic-plus-potential energy to get Eₙ proportional to −1/n²; hydrogen’s constants give −13.6 eV/n².', 'This introductory model omits reduced-mass, fine-structure and multi-electron corrections.'),
  'atomic-molecular-orbitals': r('Assume A and B are the only two mutually exclusive outcomes of a normalized measurement.', 'Normalization says the probabilities of all possible outcomes total one.', 'Because the complete set is A together with B, P(A) + P(B) = 1.'),
  'atomic-molecular-bonds': r('Bond dissociation energy is defined as the energy required to separate bound constituents under a specified reference state.', 'Start with energy Ebound and finish with higher separated energy Eseparated.', 'Final minus initial energy gives D = Eseparated − Ebound.'),
  'atomic-molecular-lasers': r('For two levels of equal degeneracy in a simplified laser model, gain needs more particles in the upper level than the lower.', 'Stimulated emission events scale with upper-level population N₂; absorption events scale with lower-level population N₁.', 'Net stimulated gain is positive when N₂ − N₁ > 0, equivalently N₂ > N₁.', 'Unequal degeneracies and spectral cross sections require a more careful gain criterion.'),

  'nuclear-binding': r('Einstein’s mass–energy relation is the physical premise; binding energy compares separated and bound system masses.', 'Compute mass defect Δm = sum of separated constituent masses minus bound nucleus mass.', 'Multiply the positive defect by c² to obtain released binding energy B = Δmc².'),
  'nuclear-decay': r('Assume each undecayed nucleus has independent constant decay probability λ per unit time.', 'For N nuclei, expected decays in short time Δt are approximately λNΔt.', 'Divide by Δt to get activity, the expected decay rate A = λN.'),
  'nuclear-half-life': r('Assume a constant independent decay probability λ for each nucleus, so population decreases exponentially.', 'The rate equation dN/dt = −λN gives N = N₀e^(−λt).', 'By definition N(t½) = N₀/2, so λ = ln 2/t½; substitute to get N = N₀·2^(−t/t½).', 'The differential equation says each remaining nucleus contributes the same small chance of decay per unit time.'),
  'nuclear-fission': r('For a reaction at rest with negligible untracked energy, mass–energy conservation relates initial and final rest masses.', 'Find the mass decrease Δm = mᵢ − mᶠ for the chosen initial and final products.', 'Multiply by c² to obtain available reaction energy Q = (mᵢ − mᶠ)c².'),
  'nuclear-fusion': r('Assume each of Nᵣ identical reactions releases the same energy Q and count all relevant reactions.', 'One reaction contributes Q; two contribute Q + Q.', 'Adding Q exactly Nᵣ times gives total E = NᵣQ.'),

  'particle-relativistic-particles': r('Special relativity gives invariant rest mass through E² − p²c² = m²c⁴.', 'Move p²c² to the right of the invariant relation.', 'Obtain E² = (pc)² + (mc²)²; use the positive root for positive-energy particles.', 'For a massless particle, this reduces to E = pc; for a particle at rest it gives E = mc².'),
  'particle-quantum-fields': r('The energy difference of adjacent free bosonic field-mode occupation levels is the quantum hf.', 'Write mode energies for n and n + 1 excitations; their shared baseline cancels on subtraction.', 'The remaining difference is one excitation quantum, ΔE = hf. This does not give interaction probabilities.'),
  'particle-symmetries': r('Electric charge conservation is an experimentally supported symmetry principle for an isolated reaction.', 'Add signed charges of every incoming particle to obtain Qbefore.', 'Add signed charges of every outgoing particle; conservation requires equality with Qbefore.'),
  'particle-standard-model': r('A proton consists of two up quarks and one down quark in the simplified valence picture.', 'Charge adds across constituents: Qp = Qu + Qu + Qd.', 'Combine the two identical terms to get Qp = 2Qu + Qd; with +2/3 and −1/3 elementary charge this is +1.'),
  'particle-neutrinos-and-open-questions': r('In a two-state oscillation approximation, a neutrino state is a mixture of two propagation states with angle θ.', 'The transition amplitude contains sin(2θ) times sin φ, where φ is the accumulated relative phase.', 'Square amplitude magnitude to obtain P = sin²(2θ) sin²φ, between zero and one.', 'Real neutrinos require three flavors and matter effects; this is a two-state illustration.'),

  'condensed-matter-lattices': r('A one-dimensional ideal lattice is defined as equally spaced sites with separation a from a chosen origin.', 'The first site after the origin is at a; the second is at a + a = 2a.', 'Repeating the same displacement n times places site n at xₙ = na.'),
  'condensed-matter-bands': r('The band gap is defined as the energy difference between conduction-band edge Ec and valence-band edge Ev.', 'A carrier promoted from Ev to Ec must gain the final energy minus initial energy.', 'Subtract Ev from Ec to obtain Eg = Ec − Ev, positive for an ordinary gap.'),
  'condensed-matter-fermi-statistics': r('Fermi–Dirac occupancy is a quantum statistical result for independent fermion states in thermal equilibrium.', 'For one state, compare empty weight 1 with occupied weight exp(−(E − μ)/(kBT)).', 'Occupied weight divided by the sum of both weights simplifies to 1/[exp((E − μ)/(kBT)) + 1].', 'Fermions permit at most one particle per single-particle state; μ is chemical potential, not mobility.'),
  'condensed-matter-semiconductors': r('In a one-carrier Drude approximation, current density equals charge density times drift speed.', 'For carrier number density n and charge magnitude e, J = nevd.', 'Mobility is defined by vd = μeE, so J = neμeE. Comparing with J = σE gives σ = neμe.', 'This omits holes, temperature dependence and scattering details.'),
  'condensed-matter-superconductivity': r('The factor 1.76 is a result of weak-coupling BCS theory, not something determined by dimensional analysis alone.', 'The theory relates zero-temperature gap to critical thermal energy by 2Δ₀/(kBTc) ≈ 3.53.', 'Divide both sides by two to obtain Δ₀ ≈ 1.76kBTc.', 'Strong-coupling and unconventional superconductors need not obey this ratio.'),

  'astrophysics-stellar-light': r('Assume a spherical star radiates approximately as a blackbody at effective temperature T.', 'A blackbody surface emits power per area F = σT⁴ by the Stefan–Boltzmann law.', 'Multiply by spherical surface area 4πR² to obtain total luminosity L = 4πR²σT⁴.'),
  'astrophysics-hydrostatic-balance': r('A star in local hydrostatic equilibrium balances pressure force against weight in each thin layer.', 'A shell element of thickness Δr and area A has mass approximately ρAΔr and inward weight ρgAΔr.', 'Outward pressure-force difference is −ΔP·A; equate forces and cancel A to obtain ΔP = −ρgΔr.', 'Density and gravity must be nearly constant across this small shell for the finite-difference form.'),
  'astrophysics-fusion': r('Mass–energy conversion is the premise; ε is the stated fraction of fuel mass converted to released energy.', 'The converted mass amount is εm rather than all of m.', 'Multiply by c² to obtain released energy E = εmc², before accounting for escaping neutrinos or other losses.'),
  'astrophysics-stellar-evolution': r('This is an order-of-magnitude estimate that assumes nearly constant luminosity and a known usable fuel energy.', 'Luminosity is energy radiated per time, L ≈ Efuel/t.', 'Rearrange by multiplying by t and dividing by L: t ≈ Efuel/L.'),
  'astrophysics-compact-objects': r('For a nonrotating uncharged black hole, the exact Schwarzschild solution of general relativity defines the horizon radius.', 'The solution’s radial factor vanishes when 1 − 2GM/(rc²) = 0.', 'Solve that equality for r to obtain rs = 2GM/c².', 'The Newtonian escape-speed argument gives the same scale but is not a proof of the relativistic horizon.'),

  'cosmology-frontiers-expansion': r('At small redshift and approximately uniform present expansion, Hubble’s law is an observationally supported local relation.', 'Expansion rate H₀ has units of inverse time; multiply by a nearby proper distance d.', 'The product has speed units and gives recession speed v ≈ H₀d in the local low-redshift regime.'),
  'cosmology-frontiers-cosmic-background': r('For freely propagating radiation in an expanding universe, wavelength stretches with scale factor a.', 'Photon frequency is inversely proportional to wavelength, so its blackbody temperature scales as 1/a.', 'Redshift is defined by 1 + z = a₀/a; with present temperature T₀, earlier temperature is T = T₀(1 + z).', 'This treats the cosmic background as an expanding blackbody spectrum, not local gas heating.'),
  'cosmology-frontiers-dark-matter-evidence': r('Assume a nearly circular orbit and approximately spherical Newtonian mass distribution within radius r.', 'Match inward acceleration v²/r with gravity GM(<r)/r².', 'Multiply by r² and divide by G to solve M(<r) = v²r/G.', 'Galaxies also need geometry, pressure and noncircular-motion corrections; this is a diagnostic estimate.'),
  'cosmology-frontiers-dark-energy-evidence': r('The equation-of-state parameter is a definition comparing effective pressure with energy density.', 'For mass-equivalent density ρ, energy density is ρc² in joules per cubic meter.', 'Divide pressure p by that energy density to obtain dimensionless w = p/(ρc²). This does not identify the physical cause.'),
  'cosmology-frontiers-tested-knowledge-versus-proposals': r('This is a normalized residual definition for comparing one observation O with a prediction P and stated nonzero uncertainty u.', 'Subtract prediction from observation to obtain residual O − P.', 'Divide by uncertainty scale u to obtain r = (O − P)/u; the sign tells which side of prediction the observation lies.', 'A residual alone is not a probability or a discovery significance without a validated error model.'),
};
