import { starterCourse, up } from './shared';
export const condensedMatterCourse = starterCourse({
  id: 'condensed-matter',
  title: 'Condensed Matter',
  group: 'modern',
  color: '#60b8a7',
  model: 'condensed',
  description: 'Connect ordered lattices, energy bands, fermion occupancy, semiconductors, and superconductivity.',
  sources: [up(3, '9-3-bonding-in-crystalline-solids'), up(3, '9-4-free-electron-model-of-metals'), up(3, '9-5-band-theory-of-solids'), up(3, '9-7-semiconductor-devices'), up(3, '9-8-superconductivity')],
  limitations: ['The lab computes independent-fermion equilibrium occupancy at prescribed energy and chemical potential. It has no density of states, band-structure solver, transport, or superconducting interactions.'],
  missions: [
        {
    id: 'lattices',
    title: 'Lattices',
    summary: 'Repeating crystal geometry supplies a spatial pattern in which electrons and vibrations behave collectively.',
    body: ['A lattice describes repeated positions generated by translations. A crystal also has a basis: the atom or group associated with each lattice point, so a lattice point is not always one atom.', 'A one-dimensional chain illustrates periodicity with positions separated by a fixed spacing. Real solids can contain defects and finite boundaries that break the ideal repetition.'],
    equation: 'x_n=na',
    symbols: [['x_n', 'position of site n in a one-dimensional chain, m'], ['n', 'integer site index'], ['a', 'positive lattice spacing, m']],
    math: 'coordinates',
    mathNotes: ['Multiply an integer by the spacing to locate a site. Negative indices mark the other side of the chosen origin; the index is not a measured length.'],
    example: {
      question: 'For spacing 0.3 nm, locate site n=4.',
      steps: ['Convert a=3×10⁻¹⁰ m.', 'Multiply by 4.'],
      answer: '1.2×10⁻⁹ m from the origin.'
            },
    calculation: ['For a=2e-10 m, find x at n=3.', 6e-10, 'm', 'The site position is 3×2×10⁻¹⁰=6×10⁻¹⁰ m.'],
    predict: ['Must every lattice point represent exactly one atom?', ['No', 'Yes'], 0, 'A basis can attach several atoms to each lattice point.'],
    check: ['What does a defect change?', ['The perfect periodic arrangement locally', 'The definition of every SI unit'], 0, 'Defects interrupt the ideal repeating structure while leaving the unit system unchanged.'],
    lab: 'Inspect the occupancy lab’s energy, chemical potential, and temperature controls. Change energy and note the occupancy response. There is no lattice-spacing control: this model uses a state’s supplied energy without deriving it from atomic geometry.',
    takeaway: 'Separate lattice geometry, atomic basis, and the energies supported by a solid.',
    limitation: 'The one-dimensional chain is a geometry example, and the occupancy model does not compute crystal structures.'
        },
        {
    id: 'bands',
    title: 'Bands',
    summary: 'Allowed energy bands and forbidden gaps describe which electronic energies a periodic solid can support.',
    body: ['When many atoms interact in a solid, isolated atomic levels broaden into collections of allowed energies. The band structure concerns allowed states, while occupancy asks which of those states are filled.', 'A gap is an energy range without the relevant bulk electronic states. Giving an occupancy formula an energy inside a gap does not create a state there; a density-of-states model is needed too.'],
    equation: 'E_g=E_c-E_v',
    symbols: [['E_g', 'band-gap energy, J'], ['E_c', 'conduction-band edge, J'], ['E_v', 'valence-band edge, J'], ['-', 'subtract lower edge from upper']],
    math: 'signed-numbers',
    mathNotes: ['Use both band edges relative to the same energy reference. Subtracting a negative lower edge is addition of its magnitude.'],
    example: {
      question: 'A toy valence edge is −2 units and conduction edge +1 unit. Find the gap.',
      steps: ['Write the difference 1−(−2).', 'Add 1+2.'],
      answer: '3 energy units.'
            },
    calculation: ['The valence edge is −3 units and conduction edge +2 units. Find the gap.', 5, 'energy units', 'The edge difference is 2−(−3)=5 units.'],
    predict: ['Does nonzero occupancy probability prove a state exists at that energy?', ['Yes', 'No'], 1, 'Occupancy is conditional on an available state; a gap may contain none in the ideal bulk model.'],
    check: ['Which describes the gap?', ['An energy interval lacking the relevant allowed states', 'An empty physical crack between atoms'], 0, 'A band gap is in energy space, not a macroscopic hole in the solid.'],
    lab: 'Scan energy through the chemical potential in the occupancy lab. Observe the smooth probability curve, then mark hypothetical band edges separately. The curve cannot reveal a gap because no density of states is included.',
    takeaway: 'Keep state availability separate from state occupancy.',
    limitation: 'The toy edge subtraction is not a computed band structure, and defects can introduce states in a real material’s gap.'
        },
        {
    id: 'fermi-statistics',
    title: 'Fermi statistics',
    summary: 'Fermions fill individual states with a temperature-dependent probability constrained by exclusion.',
    body: ['For independent fermions in equilibrium, the Fermi–Dirac distribution gives the mean occupancy of one quantum state. Its value lies between zero and one, consistent with exclusion per state.', 'At energy equal to chemical potential, occupancy is one half at any positive temperature. Raising temperature smooths the transition without automatically setting the material’s chemical potential or total carrier count.'],
    equation: 'f(E)=1/(\\exp((E-\\mu)/(k_BT))+1)',
    symbols: [['f(E)', 'mean occupancy of one fermion state'], ['E', 'state energy, J'], ['\\mu', 'chemical potential, J'], ['k_B', 'Boltzmann constant, J/K'], ['T', 'positive temperature, K'], ['\\exp(z)', 'e raised to dimensionless z'], ['+', 'add one after exponentiation'], ['-', 'energy offset from chemical potential']],
    math: 'powers',
    mathNotes: ['Subtract μ from E, divide by kBT, exponentiate, add one, then take the reciprocal. At zero offset exp(0)=1, so the denominator is two.'],
    example: {
      question: 'What is f when E=μ at positive temperature?',
      steps: ['The exponent is zero and exp(0)=1.', 'Compute 1/(1+1).'],
      answer: '0.5.'
            },
    calculation: ['If exp((E−μ)/(kBT))=3, find occupancy.', 0.25, 'probability', 'Add one to the exponential value, then invert: 1/(3+1)=0.25.'],
    predict: ['At E=μ, raising positive temperature changes f how?', ['It stays one half', 'It becomes one'], 0, 'The energy offset remains zero, leaving f=1/2.'],
    check: ['Can this independent-state fermion occupancy exceed one?', ['Yes', 'No'], 1, 'Exclusion bounds the occupancy of an individual quantum state between zero and one.'],
    lab: 'Set energy equal to chemical potential and vary temperature; verify occupancy stays 0.5. Then hold positive energy offset fixed and raise temperature to observe occupancy approach 0.5 from below.',
    takeaway: 'Interpret Fermi occupancy as a probability per available quantum state.',
    limitation: 'Chemical potential is prescribed independently; the lab does not solve the particle-number constraint or interactions.'
        },
        {
    id: 'semiconductors',
    title: 'Semiconductors',
    summary: 'Charge transport depends on both available carriers and how readily they move.',
    body: ['A semiconductor’s filled valence band and nearly empty conduction band are separated by a gap. Temperature and dopants can change electron and hole populations dramatically.', 'In an electron-only low-field transport approximation, conductivity is density times elementary charge times mobility. Occupancy alone is insufficient: counting states and modeling scattering are also necessary.'],
    equation: '\\sigma=ne\\mu_e',
    symbols: [['\\sigma', 'electrical conductivity, S/m'], ['n', 'mobile electron density, m⁻³'], ['e', 'positive elementary charge, C'], ['\\mu_e', 'electron mobility, m²/(V·s)']],
    math: 'ratios',
    mathNotes: ['Multiply three positive factors. Mobility μe is different from the chemical potential μ in the occupancy equation; the units distinguish them.'],
    example: {
      question: 'Use n=10²⁰ m⁻³, e≈1.6×10⁻¹⁹ C, and mobility 0.1 m²/(V·s).',
      steps: ['Multiply n by e to obtain 16 C/m³.', 'Multiply by mobility 0.1.'],
      answer: '1.6 S/m.'
            },
    calculation: ['At fixed mobility and charge, conductivity is 4 S/m. Find it after doubling mobile electron density.', 8, 'S/m', 'The electron-only formula is proportional to density, so conductivity doubles to 8 S/m.'],
    predict: ['Can carrier occupancy alone determine conductivity?', ['No', 'Yes'], 0, 'Conductivity also needs the number of states and mobility or scattering information.'],
    check: ['Are mobility and chemical potential the same quantity because both use μ?', ['Yes', 'No'], 1, 'They have different meanings and units; notation must be read in context.'],
    lab: 'At a fixed energy above chemical potential, raise temperature and observe occupancy increase. Explain that a conductivity prediction would also require available-state density and mobility; this lab supplies neither.',
    takeaway: 'Connect semiconductor occupancy to carriers without equating probability with conductivity.',
    limitation: 'The transport formula omits holes, high-field effects, and detailed scattering; no device current-voltage curve is simulated.'
        },
        {
    id: 'superconductivity',
    title: 'Superconductivity',
    summary: 'Superconductivity combines vanishing DC resistance with magnetic-field expulsion under suitable conditions.',
    body: ['A superconducting state is a collective quantum state, not merely a metal with many filled states. Zero DC resistance and the Meissner effect distinguish its electromagnetic response.', 'Weak-coupling conventional BCS theory relates the zero-temperature gap to transition temperature. It successfully describes many conventional superconductors, while mechanisms in unconventional materials remain active research.'],
    equation: '\\Delta_0\\approx1.76k_BT_c',
    symbols: [['\\Delta_0', 'zero-temperature single-particle gap parameter, J'], ['k_B', 'Boltzmann constant, J/K'], ['T_c', 'transition temperature, K'], ['\\approx', 'approximate weak-coupling BCS relation']],
    math: 'ratios',
    mathNotes: ['Multiply Tc by kB and the dimensionless factor 1.76. The full pair-breaking energy scale is 2Δ₀; do not confuse it with Δ₀.'],
    example: {
      question: 'Using kB≈1.38×10⁻²³, estimate Δ₀ for Tc=10 K.',
      steps: ['Compute kBTc=1.38×10⁻²² J.', 'Multiply by 1.76.'],
      answer: 'About 2.43×10⁻²² J.'
            },
    calculation: ['Within the same weak-coupling formula, doubling Tc changes a gap of 3 units to what?', 6, 'energy units', 'The approximate gap is proportional to transition temperature, so it doubles to 6 units.'],
    predict: ['Does Fermi occupancy alone produce superconductivity?', ['Yes', 'No'], 1, 'Pairing and collective interactions are absent from an independent-fermion occupancy model.'],
    check: ['Is the 1.76 relation universal for every superconductor?', ['No', 'Yes'], 0, 'It is a weak-coupling conventional BCS result, not a universal ratio for unconventional materials.'],
    lab: 'Lower temperature in the occupancy lab and observe a sharper occupation edge. Explain why this alone does not demonstrate pairing, a superconducting gap, zero resistance, or magnetic-field expulsion.',
    takeaway: 'Separate established superconducting effects from model-dependent microscopic descriptions.',
    limitation: 'The BCS gap relation is restricted to its conventional weak-coupling regime; the lab has no superconducting phase transition.'
        },
    ],
});
